# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: apis/protobuf/main/userv1/userv1.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    AsyncIterable,
    AsyncIterator,
    Dict,
    Iterable,
    List,
    Optional,
    Union,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ...meta import v1 as __meta_v1__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class GetStatusResponseUserSpecType(betterproto.Enum):
    TYPE_UNKNOWN = 0
    """TYPE_UNKNOWN is reserved. Not used by any User."""

    HUMAN = 1
    """HUMAN means that the User is used by a human."""

    WORKLOAD = 2
    """
    WORKLOAD means that the User is used by a workload (e.g. container,
     pod, sdk, server, etc...)
    """


class GetStatusResponseSessionStatusType(betterproto.Enum):
    UNKNOWN = 0
    CLIENT = 1
    """CLIENT is meant for client-based Sessions (i.e. the octelium client)"""

    CLIENTLESS = 2
    """CLIENTLESS is meant for client-less/BeyondCorp-based Sessions"""


class ConnectRequestInitializeL3Mode(betterproto.Enum):
    BOTH = 0
    """
    BOTH informs the Cluster that the Connection is ready for dual-stack.
    """

    V4 = 1
    """V4 informs the Cluster that the Connection only accepts IPv4."""

    V6 = 2
    """V6 informs the Cluster that the Connection only accepts IPv6."""


class ConnectRequestInitializeConnectionType(betterproto.Enum):
    UNSET = 0
    """UNSET is not used"""

    WIREGUARD = 1
    """WIREGUARD means that the connection is WireGuard"""

    QUICV0 = 2
    """QUICV0 means that the connection is QUICv0"""


class HostedServiceL4Type(betterproto.Enum):
    L4_UNKNOWN = 0
    """L4_UNKNOWN is not used"""

    TCP = 1
    """TCP means that the Service is TCP-based"""

    UDP = 2
    """UDP means that the Service is UDP-based"""


class HostedServiceMode(betterproto.Enum):
    MODE_UNSET = 0
    """MODE_UNSET is not used"""

    MODE_DEFAULT = 1
    """MODE_DEFAULT means that the hosted Service is served by an upstream"""

    MODE_ESSH = 2
    """
    MODE_ESSH means that the host Service is served by the embedded SSH
     server
    """


class ConnectionStateL3Mode(betterproto.Enum):
    BOTH = 0
    """BOTH approves that the Connection is ready for dual-stack."""

    V4 = 1
    """V4 approves that the Connection is ready for IPv4 only."""

    V6 = 2
    """V6 approves that the Connection is ready for IPv6 only."""


class ServiceSpecType(betterproto.Enum):
    UNSET = 0
    TCP = 1
    UDP = 2
    HTTP = 3
    SSH = 4
    KUBERNETES = 5
    POSTGRES = 6
    MYSQL = 7
    GRPC = 8
    WEB = 9
    DNS = 10


class SetServiceConfigsResponseL3Mode(betterproto.Enum):
    BOTH = 0
    V4 = 1
    V6 = 2


@dataclass(eq=False, repr=False)
class LogoutRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class LogoutResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetStatusRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetStatusResponse(betterproto.Message):
    domain: str = betterproto.string_field(1)
    cluster: "GetStatusResponseCluster" = betterproto.message_field(2)
    """Cluster is the Cluster's information."""

    user: "GetStatusResponseUser" = betterproto.message_field(3)
    """User is the User's information."""

    session: "GetStatusResponseSession" = betterproto.message_field(4)
    """Session is the Session's information."""


@dataclass(eq=False, repr=False)
class GetStatusResponseUser(betterproto.Message):
    metadata: "__meta_v1__.Metadata" = betterproto.message_field(1)
    spec: "GetStatusResponseUserSpec" = betterproto.message_field(2)
    status: "GetStatusResponseUserStatus" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class GetStatusResponseUserSpec(betterproto.Message):
    email: str = betterproto.string_field(1)
    type: "GetStatusResponseUserSpecType" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class GetStatusResponseUserStatus(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetStatusResponseSession(betterproto.Message):
    metadata: "__meta_v1__.Metadata" = betterproto.message_field(1)
    spec: "GetStatusResponseSessionSpec" = betterproto.message_field(2)
    status: "GetStatusResponseSessionStatus" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class GetStatusResponseSessionSpec(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetStatusResponseSessionStatus(betterproto.Message):
    type: "GetStatusResponseSessionStatusType" = betterproto.enum_field(1)
    is_connected: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class GetStatusResponseCluster(betterproto.Message):
    metadata: "__meta_v1__.Metadata" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ConnectRequest(betterproto.Message):
    initialize: "ConnectRequestInitialize" = betterproto.message_field(1, group="type")
    keep_alive: "ConnectRequestKeepAlive" = betterproto.message_field(2, group="type")


@dataclass(eq=False, repr=False)
class ConnectRequestInitialize(betterproto.Message):
    l3_mode: "ConnectRequestInitializeL3Mode" = betterproto.enum_field(1)
    """L3Mode is the layer-3 mode supported by the Connection."""

    service_options: "ConnectRequestInitializeServiceOptions" = (
        betterproto.message_field(2)
    )
    """
    ServiceOptions sets the hosted Services to be served by the Connection.
    """

    connection_type: "ConnectRequestInitializeConnectionType" = betterproto.enum_field(
        3
    )
    """ConnectionType is the connection type"""

    published_services: List["ConnectRequestInitializePublishedService"] = (
        betterproto.message_field(4)
    )
    """
    PublishedServices is the list of published Services to the client host
    """

    ignore_dns: bool = betterproto.bool_field(5)
    """IgnoreDNS means that the client does not used the Cluster DNS"""

    e_ssh_enable: bool = betterproto.bool_field(6)
    """EnableESSH enables serving embedded SSH"""

    e_ssh_port: int = betterproto.int32_field(7)
    """Port is the listen port of the embedded SSH server"""


@dataclass(eq=False, repr=False)
class ConnectRequestInitializeServiceOptions(betterproto.Message):
    serve_all: bool = betterproto.bool_field(1)
    """
    ServeAll informs the Cluster that Connection is ready to serve all
     Services that can be hosted by the owner User.
    """

    services: List["ConnectRequestInitializeServiceOptionsService"] = (
        betterproto.message_field(2)
    )
    label_selector: str = betterproto.string_field(3)
    port_start: int = betterproto.int32_field(4)
    """
    PortStart informs the Cluster of the initial port number that should be
     used for serving Services.
    """


@dataclass(eq=False, repr=False)
class ConnectRequestInitializeServiceOptionsService(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ConnectRequestInitializePublishedService(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Name is the Service name"""

    port: int = betterproto.uint32_field(2)
    """Port is the forwarded Service port number on the client host"""

    address: str = betterproto.string_field(3)
    """Address is the forwarded Service host address"""


@dataclass(eq=False, repr=False)
class ConnectRequestKeepAlive(betterproto.Message):
    set_at: datetime = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class DisconnectRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DisconnectResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class Gateway(betterproto.Message):
    id: str = betterproto.string_field(1)
    """ID is the Gateway's ID."""

    addresses: List[str] = betterproto.string_field(2)
    """Addresses is the list of the Gateway's public addresses."""

    cid_rs: List[str] = betterproto.string_field(3)
    """CIDRs is the list of Gateway CIDRs."""

    hostname: str = betterproto.string_field(4)
    wireguard: "GatewayWireGuard" = betterproto.message_field(5)
    quicv0: "GatewayQuicv0" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class GatewayWireGuard(betterproto.Message):
    port: int = betterproto.int32_field(1)
    """Port is the Gateway's WireGuard port."""

    public_key: str = betterproto.string_field(2)
    """PublicKey is the Gateway's WireGuard curve25519 public key."""

    keep_alive_seconds: int = betterproto.int32_field(3)
    """
    CIDRs is the list of Gateway CIDRs.
     KeepAliveSeconds is the number of seconds to periodically send
     WireGuard's keepalive packets.
    """


@dataclass(eq=False, repr=False)
class GatewayQuicv0(betterproto.Message):
    port: int = betterproto.int32_field(1)
    """Port is the Gateway's QUICv0 port."""

    keep_alive_seconds: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class Dns(betterproto.Message):
    servers: List[str] = betterproto.string_field(1)
    """Servers is the list of the Cluster private DNS servers."""


@dataclass(eq=False, repr=False)
class HostedService(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Name is the name of the hosted Service."""

    port: int = betterproto.uint32_field(2)
    """Port is the Service's port."""

    l4_type: "HostedServiceL4Type" = betterproto.enum_field(3)
    """L4Type is the layer-4 type of the Service."""

    upstream: "HostedServiceUpstream" = betterproto.message_field(4)
    """Upstream is the listener upstream's information."""

    address: "__meta_v1__.DualStackIp" = betterproto.message_field(5)
    """
    Address is the dual-stack address of the Service. It can be null for
     upstreams listening on 0.0.0.0 or the Connection addresses.
    """

    mode: "HostedServiceMode" = betterproto.enum_field(6)
    """Mode is the hosted Service mode"""


@dataclass(eq=False, repr=False)
class HostedServiceUpstream(betterproto.Message):
    host: str = betterproto.string_field(1)
    """Host is the upstream host"""

    port: int = betterproto.int32_field(2)
    """Port is the upstream listen port"""


@dataclass(eq=False, repr=False)
class ConnectionState(betterproto.Message):
    mtu: int = betterproto.int32_field(1)
    """MTU is the link MTU used at the client side"""

    x25519_key: bytes = betterproto.bytes_field(2)
    """X25519Key is the WireGuard private key used by the client"""

    ed25519_key: bytes = betterproto.bytes_field(3)
    addresses: List["__meta_v1__.DualStackNetwork"] = betterproto.message_field(4)
    """Addresses is the list of the dual-stack addresses of the Connection."""

    gateways: List["Gateway"] = betterproto.message_field(5)
    """Gateways is the list of the Gateways."""

    dns: "Dns" = betterproto.message_field(6)
    """DNS sets the private DNS information."""

    service_configs: List["ConnectionStateServiceConfig"] = betterproto.message_field(7)
    """ServiceConfigs is the list of Service configs set to the client host"""

    l3_mode: "ConnectionStateL3Mode" = betterproto.enum_field(8)
    """L3Mode sets the layer-3 mode approved by the Cluster."""

    service_options: "ConnectionStateServiceOptions" = betterproto.message_field(9)
    """ServiceOptions is the hosted Service information."""

    cidr: "__meta_v1__.DualStackNetwork" = betterproto.message_field(10)
    """CIDR is the Cluster Service CIDR."""


@dataclass(eq=False, repr=False)
class ConnectionStateServiceOptions(betterproto.Message):
    services: List["HostedService"] = betterproto.message_field(1)
    """HostedServices is the list of hosted Services"""


@dataclass(eq=False, repr=False)
class ConnectionStateServiceConfig(betterproto.Message):
    ssh: "ConnectionStateServiceConfigSsh" = betterproto.message_field(1, group="type")
    """SSH sets SSH-specific Service config"""


@dataclass(eq=False, repr=False)
class ConnectionStateServiceConfigSsh(betterproto.Message):
    known_hosts: List[str] = betterproto.string_field(1)
    """KnownHosts is the list of SSH known hosts"""

    authorized_keys: List[str] = betterproto.string_field(2)
    """AuthorizedKeys is the list of SSH authorized keys"""


@dataclass(eq=False, repr=False)
class Service(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    kind: str = betterproto.string_field(2)
    metadata: "__meta_v1__.Metadata" = betterproto.message_field(3)
    spec: "ServiceSpec" = betterproto.message_field(4)
    status: "ServiceStatus" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class ServiceSpec(betterproto.Message):
    port: int = betterproto.uint32_field(1)
    """Port is the Service listen port"""

    type: "ServiceSpecType" = betterproto.enum_field(2)
    """Type is the Service tpye"""

    is_tls: bool = betterproto.bool_field(3)
    """IsTLS shows whether the Service is listening over TLS"""

    is_public: bool = betterproto.bool_field(4)
    """
    IsPublic means that the Service is publicly exposed and can be accessed
     via the client-less/BeyondCorp mode
    """


@dataclass(eq=False, repr=False)
class ServiceStatus(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    """Namespace is the Service's Namespace"""

    addresses: List[str] = betterproto.string_field(2)
    """Addresses is the list of private addresses used by the Service"""

    primary_hostname: str = betterproto.string_field(3)
    """PrimaryHostname is the unique primary hostname"""


@dataclass(eq=False, repr=False)
class ServiceList(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    kind: str = betterproto.string_field(2)
    items: List["Service"] = betterproto.message_field(3)
    list_response_meta: "__meta_v1__.ListResponseMeta" = betterproto.message_field(4)
    """ListResponseMeta is common information about the list."""


@dataclass(eq=False, repr=False)
class ListServiceOptions(betterproto.Message):
    common: "__meta_v1__.CommonListOptions" = betterproto.message_field(1)
    namespace: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ListNamespaceOptions(betterproto.Message):
    common: "__meta_v1__.CommonListOptions" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Namespace(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    kind: str = betterproto.string_field(2)
    metadata: "__meta_v1__.Metadata" = betterproto.message_field(3)
    """Metadata is the object's metadata."""

    spec: "NamespaceSpec" = betterproto.message_field(4)
    """Spec is the Namespace specification."""

    status: "NamespaceStatus" = betterproto.message_field(5)
    """Status is the current status of the Namespace."""


@dataclass(eq=False, repr=False)
class NamespaceSpec(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class NamespaceStatus(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class NamespaceList(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    """APIVersion is the API version of the object."""

    kind: str = betterproto.string_field(2)
    """Kind is the resource name (i.e. `NamespaceList`)."""

    items: List["Namespace"] = betterproto.message_field(3)
    """Items is the list of Namespaces."""

    list_response_meta: "__meta_v1__.ListResponseMeta" = betterproto.message_field(4)
    """ListResponseMeta is common information about the list."""


@dataclass(eq=False, repr=False)
class ConnectResponse(betterproto.Message):
    created_at: datetime = betterproto.message_field(11)
    add_gateway: "ConnectResponseAddGateway" = betterproto.message_field(
        1, group="Event"
    )
    """AddGateway is the event to add a Gateway."""

    update_gateway: "ConnectResponseUpdateGateway" = betterproto.message_field(
        2, group="Event"
    )
    """UpdateGateway is the event to update a Gateway."""

    delete_gateway: "ConnectResponseDeleteGateway" = betterproto.message_field(
        3, group="Event"
    )
    """DeleteGateway is the event to delete a Gateway."""

    update_dns: "ConnectResponseUpdateDns" = betterproto.message_field(4, group="Event")
    """UpdateDNS is the event to update DNS."""

    message: "ConnectResponseMessage" = betterproto.message_field(5, group="Event")
    """Message is the event to receive a custom message from the Cluster."""

    disconnect: "ConnectResponseDisconnect" = betterproto.message_field(
        6, group="Event"
    )
    """Disconnect is the event to disconnect from the Cluster."""

    add_service: "ConnectResponseAddService" = betterproto.message_field(
        7, group="Event"
    )
    """AddService is the event to add a hosted Service."""

    update_service: "ConnectResponseUpdateService" = betterproto.message_field(
        8, group="Event"
    )
    """UpdateService is the event to update a hosted Service."""

    delete_service: "ConnectResponseDeleteService" = betterproto.message_field(
        9, group="Event"
    )
    """DeleteService is the event to delete a hosted Service."""

    state: "ConnectionState" = betterproto.message_field(10, group="Event")
    """State is the event that sends the entire state of the Connection."""


@dataclass(eq=False, repr=False)
class ConnectResponseAddGateway(betterproto.Message):
    gateway: "Gateway" = betterproto.message_field(1)
    """Gateway is the added Gateway."""


@dataclass(eq=False, repr=False)
class ConnectResponseUpdateGateway(betterproto.Message):
    gateway: "Gateway" = betterproto.message_field(1)
    """Gateway is the updated Gateway."""


@dataclass(eq=False, repr=False)
class ConnectResponseDeleteGateway(betterproto.Message):
    id: str = betterproto.string_field(1)
    """ID is the ID of the Gateway that needs to be deleted."""


@dataclass(eq=False, repr=False)
class ConnectResponseDisconnect(betterproto.Message):
    message: str = betterproto.string_field(1)
    """
    Message is an optional message from the Cluster upon disconnect.
     Currrently not used.
    """


@dataclass(eq=False, repr=False)
class ConnectResponseMessage(betterproto.Message):
    message: str = betterproto.string_field(1)
    """Message is a custom message from the Cluster."""


@dataclass(eq=False, repr=False)
class ConnectResponseUpdateDns(betterproto.Message):
    dns: "Dns" = betterproto.message_field(1)
    """DNS is the DNS information."""


@dataclass(eq=False, repr=False)
class ConnectResponseAddService(betterproto.Message):
    service: "HostedService" = betterproto.message_field(1)
    """Service is the hosted Service that needs to be added."""


@dataclass(eq=False, repr=False)
class ConnectResponseUpdateService(betterproto.Message):
    service: "HostedService" = betterproto.message_field(1)
    """Service is the hosted Service that needs to be updated."""


@dataclass(eq=False, repr=False)
class ConnectResponseDeleteService(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Name is the name of the Service that needs to be deleted."""


@dataclass(eq=False, repr=False)
class SetServiceConfigsRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Name is the Service name"""


@dataclass(eq=False, repr=False)
class SetServiceConfigsResponse(betterproto.Message):
    configs: List["SetServiceConfigsResponseConfig"] = betterproto.message_field(1)
    """
    Configs is the list of configurations needed to be set at the client side
     to use the Service
    """

    host: str = betterproto.string_field(2)
    port: int = betterproto.int32_field(3)
    l3_mode: "SetServiceConfigsResponseL3Mode" = betterproto.enum_field(4)


@dataclass(eq=False, repr=False)
class SetServiceConfigsResponseConfig(betterproto.Message):
    kubeconfig: "SetServiceConfigsResponseConfigKubeconfig" = betterproto.message_field(
        1, group="type"
    )
    """Kubeconfig sets kubeconfig-specific configurations"""

    ssh: "SetServiceConfigsResponseConfigSsh" = betterproto.message_field(
        2, group="type"
    )


@dataclass(eq=False, repr=False)
class SetServiceConfigsResponseConfigKubeconfig(betterproto.Message):
    content: bytes = betterproto.bytes_field(1)
    """Content is the kubeconfig content"""


@dataclass(eq=False, repr=False)
class SetServiceConfigsResponseConfigSsh(betterproto.Message):
    known_hosts: List[str] = betterproto.string_field(1)
    """KnownHosts is the list of SSH known hosts"""

    authorized_keys: List[str] = betterproto.string_field(2)
    """AuthorizedKeys is the list of SSH authorized keys"""


class MainServiceStub(betterproto.ServiceStub):
    async def connect(
        self,
        connect_request_iterator: Union[
            AsyncIterable[ConnectRequest], Iterable[ConnectRequest]
        ],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[ConnectResponse]:
        async for response in self._stream_stream(
            "/octelium.api.main.user.v1.MainService/Connect",
            connect_request_iterator,
            ConnectRequest,
            ConnectResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def disconnect(
        self,
        disconnect_request: "DisconnectRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DisconnectResponse":
        return await self._unary_unary(
            "/octelium.api.main.user.v1.MainService/Disconnect",
            disconnect_request,
            DisconnectResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_service(
        self,
        list_service_options: "ListServiceOptions",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ServiceList":
        return await self._unary_unary(
            "/octelium.api.main.user.v1.MainService/ListService",
            list_service_options,
            ServiceList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_namespace(
        self,
        list_namespace_options: "ListNamespaceOptions",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NamespaceList":
        return await self._unary_unary(
            "/octelium.api.main.user.v1.MainService/ListNamespace",
            list_namespace_options,
            NamespaceList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_status(
        self,
        get_status_request: "GetStatusRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetStatusResponse":
        return await self._unary_unary(
            "/octelium.api.main.user.v1.MainService/GetStatus",
            get_status_request,
            GetStatusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_service_configs(
        self,
        set_service_configs_request: "SetServiceConfigsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetServiceConfigsResponse":
        return await self._unary_unary(
            "/octelium.api.main.user.v1.MainService/SetServiceConfigs",
            set_service_configs_request,
            SetServiceConfigsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_service(
        self,
        meta_v1_get_options: "__meta_v1__.GetOptions",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Service":
        return await self._unary_unary(
            "/octelium.api.main.user.v1.MainService/GetService",
            meta_v1_get_options,
            Service,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class MainServiceBase(ServiceBase):

    async def connect(
        self, connect_request_iterator: AsyncIterator[ConnectRequest]
    ) -> AsyncIterator[ConnectResponse]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield ConnectResponse()

    async def disconnect(
        self, disconnect_request: "DisconnectRequest"
    ) -> "DisconnectResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_service(
        self, list_service_options: "ListServiceOptions"
    ) -> "ServiceList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_namespace(
        self, list_namespace_options: "ListNamespaceOptions"
    ) -> "NamespaceList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_status(
        self, get_status_request: "GetStatusRequest"
    ) -> "GetStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_service_configs(
        self, set_service_configs_request: "SetServiceConfigsRequest"
    ) -> "SetServiceConfigsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_service(
        self, meta_v1_get_options: "__meta_v1__.GetOptions"
    ) -> "Service":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_connect(
        self, stream: "grpclib.server.Stream[ConnectRequest, ConnectResponse]"
    ) -> None:
        request = stream.__aiter__()
        await self._call_rpc_handler_server_stream(
            self.connect,
            stream,
            request,
        )

    async def __rpc_disconnect(
        self, stream: "grpclib.server.Stream[DisconnectRequest, DisconnectResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.disconnect(request)
        await stream.send_message(response)

    async def __rpc_list_service(
        self, stream: "grpclib.server.Stream[ListServiceOptions, ServiceList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_service(request)
        await stream.send_message(response)

    async def __rpc_list_namespace(
        self, stream: "grpclib.server.Stream[ListNamespaceOptions, NamespaceList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_namespace(request)
        await stream.send_message(response)

    async def __rpc_get_status(
        self, stream: "grpclib.server.Stream[GetStatusRequest, GetStatusResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_status(request)
        await stream.send_message(response)

    async def __rpc_set_service_configs(
        self,
        stream: "grpclib.server.Stream[SetServiceConfigsRequest, SetServiceConfigsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_service_configs(request)
        await stream.send_message(response)

    async def __rpc_get_service(
        self, stream: "grpclib.server.Stream[__meta_v1__.GetOptions, Service]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_service(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/octelium.api.main.user.v1.MainService/Connect": grpclib.const.Handler(
                self.__rpc_connect,
                grpclib.const.Cardinality.STREAM_STREAM,
                ConnectRequest,
                ConnectResponse,
            ),
            "/octelium.api.main.user.v1.MainService/Disconnect": grpclib.const.Handler(
                self.__rpc_disconnect,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisconnectRequest,
                DisconnectResponse,
            ),
            "/octelium.api.main.user.v1.MainService/ListService": grpclib.const.Handler(
                self.__rpc_list_service,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListServiceOptions,
                ServiceList,
            ),
            "/octelium.api.main.user.v1.MainService/ListNamespace": grpclib.const.Handler(
                self.__rpc_list_namespace,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListNamespaceOptions,
                NamespaceList,
            ),
            "/octelium.api.main.user.v1.MainService/GetStatus": grpclib.const.Handler(
                self.__rpc_get_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetStatusRequest,
                GetStatusResponse,
            ),
            "/octelium.api.main.user.v1.MainService/SetServiceConfigs": grpclib.const.Handler(
                self.__rpc_set_service_configs,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetServiceConfigsRequest,
                SetServiceConfigsResponse,
            ),
            "/octelium.api.main.user.v1.MainService/GetService": grpclib.const.Handler(
                self.__rpc_get_service,
                grpclib.const.Cardinality.UNARY_UNARY,
                __meta_v1__.GetOptions,
                Service,
            ),
        }
