"""Typed sync/async Cordium SDK. See README.md for lifecycle and ownership guidance."""

from octelium.api.main.cordium import v1 as proto
from octelium.api.main.meta import v1 as meta

from ._engine import RawServices
from .auth import (
    AccessToken,
    Assertion,
    AssertionFile,
    AuthenticationToken,
    Credentials,
    TokenProvider,
)
from .client import AsyncCordium
from .errors import CordiumError, ExecError, WorkspaceFailureError
from .exec import AsyncExecSession, argv, shell_quote
from .files import AsyncFiles
from .models import ExecOutput, ExecResult, Page, Ref, Reference, TerminalEvent
from .resources import (
    AsyncGitProviders,
    AsyncManagement,
    AsyncMemberships,
    AsyncRegions,
    AsyncSecrets,
    AsyncSnapshots,
    AsyncSpaces,
    AsyncTemplates,
    AsyncUserConfig,
    AsyncUserSecrets,
    AsyncVolumes,
    JsonValue,
    Role,
    SecretValue,
)
from .spec import (
    Application,
    Resources,
    SecretRef,
    Task,
    VolumeMount,
    WorkspaceOptions,
    create_workspace_spec,
)
from .streams import AsyncStream
from .sync import (
    Cordium,
    ExecSession,
    Files,
    GitProviders,
    Management,
    Memberships,
    Regions,
    Secrets,
    Snapshots,
    Spaces,
    Stream,
    Templates,
    Terminal,
    Terminals,
    UserConfig,
    UserSecrets,
    Volumes,
    Workspace,
    Workspaces,
)
from .terminals import AsyncTerminal, AsyncTerminals
from .workspaces import AsyncWorkspace, AsyncWorkspaces, State

__all__ = [
    "proto",
    "meta",
    "RawServices",
    "AccessToken",
    "AuthenticationToken",
    "Assertion",
    "AssertionFile",
    "Credentials",
    "TokenProvider",
    "AsyncCordium",
    "CordiumError",
    "ExecError",
    "WorkspaceFailureError",
    "AsyncExecSession",
    "argv",
    "shell_quote",
    "AsyncFiles",
    "Ref",
    "Reference",
    "Page",
    "ExecOutput",
    "ExecResult",
    "TerminalEvent",
    "AsyncSpaces",
    "AsyncTemplates",
    "AsyncSnapshots",
    "AsyncVolumes",
    "AsyncSecrets",
    "AsyncUserSecrets",
    "AsyncGitProviders",
    "AsyncMemberships",
    "AsyncRegions",
    "AsyncUserConfig",
    "AsyncManagement",
    "JsonValue",
    "SecretValue",
    "Role",
    "Application",
    "Resources",
    "SecretRef",
    "Task",
    "VolumeMount",
    "WorkspaceOptions",
    "create_workspace_spec",
    "AsyncStream",
    "AsyncTerminal",
    "AsyncTerminals",
    "AsyncWorkspace",
    "AsyncWorkspaces",
    "State",
    "Cordium",
    "Workspaces",
    "Workspace",
    "ExecSession",
    "Files",
    "Terminals",
    "Terminal",
    "Stream",
    "Spaces",
    "Templates",
    "Snapshots",
    "Volumes",
    "Secrets",
    "UserSecrets",
    "GitProviders",
    "Memberships",
    "Regions",
    "UserConfig",
    "Management",
]
