"""Blocking Cordium facade. Generated by scripts/generate_sync.py; do not hand edit."""

from __future__ import annotations

import ssl
from collections.abc import AsyncIterator, Awaitable, Callable, Iterator, Mapping, Sequence
from datetime import datetime
from pathlib import Path
from types import TracebackType
from typing import Generic, Literal, TypeVar, Unpack, cast

import httpx
from octelium.api.main.cordium import v1 as p
from octelium.sdk import AuthConfig

from ._portal import Portal
from .auth import Credentials
from .client import AsyncCordium
from .exec import AsyncExecSession
from .files import AsyncFiles
from .models import ExecOutput, ExecResult, LogEntry, Page, Reference, TerminalEvent, WorkspaceEvent
from .resources import (
    AsyncGitProviders,
    AsyncManagement,
    AsyncMemberships,
    AsyncRegions,
    AsyncSecrets,
    AsyncSnapshots,
    AsyncSpaces,
    AsyncTemplates,
    AsyncUserConfig,
    AsyncUserSecrets,
    AsyncVolumes,
    JsonValue,
    Role,
    SecretValue,
)
from .spec import Resources, SecretRef, Task, VolumeMount, WorkspaceOptions
from .terminals import AsyncTerminal, AsyncTerminals
from .workspaces import AsyncWorkspace, AsyncWorkspaces, State

T = TypeVar("T")


class _Facade(Generic[T]):
    def __init__(self, portal: Portal, value: T) -> None:
        self._portal, self._async = portal, value


async def _next(iterator: AsyncIterator[T]) -> tuple[bool, T | None]:
    try:
        return True, await anext(iterator)
    except StopAsyncIteration:
        return False, None


class Stream(Generic[T]):
    """Single-consumer blocking iterator. Use with to close on early loop exit."""

    def __init__(self, portal: Portal, iterator: AsyncIterator[T]) -> None:
        self._portal, self._iterator, self._closed = portal, iterator, False

    def __iter__(self) -> Stream[T]:
        """Return this stream."""
        return self

    def __next__(self) -> T:
        """Wait for the next item; propagate server errors and deadlines."""
        if self._closed:
            raise StopIteration
        has_value, value = self._portal.invoke(lambda: _next(self._iterator))
        if not has_value:
            self._closed = True
            raise StopIteration
        from typing import cast

        return cast(T, value)

    def close(self) -> None:
        """Cancel this subscription; never delete remote resources."""
        if not self._closed:
            self._closed = True
            if hasattr(self._iterator, "aclose"):
                self._portal.release(self._iterator.aclose)

    def __enter__(self) -> Stream[T]:
        """Return the stream; closing is guaranteed on context exit."""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Release this subscription."""
        self.close()


async def _workspace_items(
    portal: Portal, iterator: AsyncIterator[AsyncWorkspace]
) -> AsyncIterator[Workspace]:
    try:
        async for item in iterator:
            yield Workspace(portal, item)
    finally:
        if hasattr(iterator, "aclose"):
            await iterator.aclose()


class Spaces(_Facade[AsyncSpaces]):
    "Space API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.Space:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        mode: Literal["owned", "member"] = "owned",
        type: Literal["user", "organization"] | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.Space]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                mode=mode,
                type=type,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        mode: Literal["owned", "member"] = "owned",
        type: Literal["user", "organization"] | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.Space]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    mode=mode,
                    type=type,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def modify(
        self, ref: Reference, mutate: Callable[[p.Space], None], *, timeout: float | None = 30
    ) -> p.Space:
        "Fetch, edit with a synchronous callback, and write once under one deadline.\n\nPreserve metadata/resource version. Callback exceptions abort the write;\nconflicts are not retried. In the blocking client the callback runs on\nits event-loop thread, so it must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(ref, mutate, timeout=timeout))

    def update(self, resource: p.Space, *, timeout: float | None = 30) -> p.Space:
        "Replace a complete fetched resource once, preserving its metadata; no automatic retry."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def create(
        self,
        name: str,
        *,
        organization: bool = False,
        display_name: str = "",
        default_resources: Resources | None = None,
        max_resources: Resources | None = None,
        env: Mapping[str, str | SecretRef] | None = None,
        disable_ssh: bool | None = None,
        spec: p.SpaceSpec | None = None,
        timeout: float | None = 30,
    ) -> p.Space:
        "Create a Space. organization=True appends .cordium to a short name.\n\nResource limits are millicores/megabytes; env values may reference Space Secrets.\nConvenience fields override their corresponding fields in a copied spec."
        return self._portal.invoke(
            lambda: self._async.create(
                name,
                organization=organization,
                display_name=display_name,
                default_resources=default_resources,
                max_resources=max_resources,
                env=env,
                disable_ssh=disable_ssh,
                spec=spec,
                timeout=timeout,
            )
        )

    def leave(self, space: Reference, *, timeout: float | None = 30) -> None:
        "Remove the caller's Space membership; creators cannot leave their own Space."
        self._portal.invoke(lambda: self._async.leave(space, timeout=timeout))


class Templates(_Facade[AsyncTemplates]):
    "Template API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.Template:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.Template]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                space=space,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.Template]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    space=space,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def modify(
        self, ref: Reference, mutate: Callable[[p.Template], None], *, timeout: float | None = 30
    ) -> p.Template:
        "Fetch, edit with a synchronous callback, and write once under one deadline.\n\nPreserve metadata/resource version. Callback exceptions abort the write;\nconflicts are not retried. In the blocking client the callback runs on\nits event-loop thread, so it must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(ref, mutate, timeout=timeout))

    def update(self, resource: p.Template, *, timeout: float | None = 30) -> p.Template:
        "Replace a complete fetched resource once, preserving its metadata; no automatic retry."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def create(
        self,
        name: str,
        *,
        image: str | p.WorkspaceSpecImage | None = None,
        repository: str | p.WorkspaceSpecRepository | None = None,
        git_provider: str | None = None,
        env: Mapping[str, str | SecretRef] | None = None,
        vars: Mapping[str, str] | None = None,
        resources: Resources | None = None,
        tasks: Sequence[Task] | None = None,
        volumes: Sequence[VolumeMount] | None = None,
        disable_timeout: bool | None = None,
        auto_stop: bool | None = None,
        display_name: str = "",
        spec: p.TemplateSpec | None = None,
        timeout: float | None = 30,
    ) -> p.Template:
        "Create a template in the Space selected by its qualified name.\n\nimage strings are registry references; spec provides lifecycle tasks, features,\nresources, variables and the other generated template fields."
        return self._portal.invoke(
            lambda: self._async.create(
                name,
                image=image,
                repository=repository,
                git_provider=git_provider,
                env=env,
                vars=vars,
                resources=resources,
                tasks=tasks,
                volumes=volumes,
                disable_timeout=disable_timeout,
                auto_stop=auto_stop,
                display_name=display_name,
                spec=spec,
                timeout=timeout,
            )
        )

    def build(
        self, template: Reference, *, tags: tuple[str, ...] = (), timeout: float | None = 30
    ) -> p.Template:
        "Start an asynchronous pre-build, optionally tagged for identification."
        return self._portal.invoke(lambda: self._async.build(template, tags=tags, timeout=timeout))

    def cancel_build(self, template: Reference, *, timeout: float | None = 30) -> p.Template:
        "Cancel the currently running pre-build."
        return self._portal.invoke(lambda: self._async.cancel_build(template, timeout=timeout))

    def wait_for_build(
        self,
        template: Reference,
        build_id: str,
        *,
        timeout: float | None = 300,
        poll_interval: float = 1,
    ) -> p.Template:
        "Wait for a specific build ID, never mistaking an older successful build for this one."
        return self._portal.invoke(
            lambda: self._async.wait_for_build(
                template, build_id, timeout=timeout, poll_interval=poll_interval
            )
        )


class Snapshots(_Facade[AsyncSnapshots]):
    "WorkspaceSnapshot API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.WorkspaceSnapshot:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        workspace: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.WorkspaceSnapshot]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                space=space,
                workspace=workspace,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        workspace: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.WorkspaceSnapshot]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    space=space,
                    workspace=workspace,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def create(
        self, name: str, workspace: Reference, *, timeout: float | None = 30
    ) -> p.WorkspaceSnapshot:
        "Snapshot persistent storage without stopping the source. Running snapshots are crash-consistent."
        return self._portal.invoke(lambda: self._async.create(name, workspace, timeout=timeout))

    def wait_until_ready(
        self, ref: Reference, *, timeout: float | None = 300, poll_interval: float = 1
    ) -> p.WorkspaceSnapshot:
        "Wait until restorable; report terminal CSI/storage failures as SNAPSHOT_FAILED."
        return self._portal.invoke(
            lambda: self._async.wait_until_ready(ref, timeout=timeout, poll_interval=poll_interval)
        )


class Volumes(_Facade[AsyncVolumes]):
    "Volume API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.Volume:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.Volume]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                space=space,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.Volume]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    space=space,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def modify(
        self, ref: Reference, mutate: Callable[[p.Volume], None], *, timeout: float | None = 30
    ) -> p.Volume:
        "Fetch, edit with a synchronous callback, and write once under one deadline.\n\nPreserve metadata/resource version. Callback exceptions abort the write;\nconflicts are not retried. In the blocking client the callback runs on\nits event-loop thread, so it must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(ref, mutate, timeout=timeout))

    def update(self, resource: p.Volume, *, timeout: float | None = 30) -> p.Volume:
        "Replace a complete fetched resource once, preserving its metadata; no automatic retry."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def create(
        self,
        name: str,
        *,
        size: int | None = None,
        shared: bool = False,
        region: Reference | None = None,
        timeout: float | None = 30,
    ) -> p.Volume:
        "Create a volume; size is megabytes. Some backends provision only after the first mount."
        return self._portal.invoke(
            lambda: self._async.create(
                name, size=size, shared=shared, region=region, timeout=timeout
            )
        )

    def grow(self, ref: Reference, megabytes: int, *, timeout: float | None = 30) -> p.Volume:
        "Grow capacity in megabytes. Shrinking is rejected; backend expansion support is required."
        return self._portal.invoke(lambda: self._async.grow(ref, megabytes, timeout=timeout))

    def wait_until_ready(
        self, ref: Reference, *, timeout: float | None = 300, poll_interval: float = 1
    ) -> p.Volume:
        "Wait for READY. Deferred provisioning may require mounting first."
        return self._portal.invoke(
            lambda: self._async.wait_until_ready(ref, timeout=timeout, poll_interval=poll_interval)
        )


class Secrets(_Facade[AsyncSecrets]):
    "Secret API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.Secret:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.Secret]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                space=space,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.Secret]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    space=space,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def create(self, name: str, value: SecretValue, *, timeout: float | None = 30) -> p.Secret:
        "Create a write-only Space Secret. Strings, bytes and JSON objects are supported; no update RPC exists."
        return self._portal.invoke(lambda: self._async.create(name, value, timeout=timeout))


class UserSecrets(_Facade[AsyncUserSecrets]):
    "UserSecret API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.UserSecret:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.UserSecret]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.UserSecret]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def modify(
        self, ref: Reference, mutate: Callable[[p.UserSecret], None], *, timeout: float | None = 30
    ) -> p.UserSecret:
        "Fetch, edit with a synchronous callback, and write once under one deadline.\n\nPreserve metadata/resource version. Callback exceptions abort the write;\nconflicts are not retried. In the blocking client the callback runs on\nits event-loop thread, so it must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(ref, mutate, timeout=timeout))

    def update(self, resource: p.UserSecret, *, timeout: float | None = 30) -> p.UserSecret:
        "Replace a complete fetched resource once, preserving its metadata; no automatic retry."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def create(self, name: str, value: SecretValue, *, timeout: float | None = 30) -> p.UserSecret:
        "Create a write-only personal Secret from text, bytes, or JSON attributes."
        return self._portal.invoke(lambda: self._async.create(name, value, timeout=timeout))

    def create_ssh_key(self, name: str, *, timeout: float | None = 30) -> p.UserSecret:
        "Ask the Cluster to generate an SSH key pair. The private key never leaves the Cluster."
        return self._portal.invoke(lambda: self._async.create_ssh_key(name, timeout=timeout))

    def set(
        self, ref: Reference, value: SecretValue, *, timeout: float | None = 30
    ) -> p.UserSecret:
        "Replace a personal Secret value, preserving its existing type and metadata."
        return self._portal.invoke(lambda: self._async.set(ref, value, timeout=timeout))


class GitProviders(_Facade[AsyncGitProviders]):
    "GitProvider API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.GitProvider:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.GitProvider]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                space=space,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.GitProvider]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    space=space,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def modify(
        self, ref: Reference, mutate: Callable[[p.GitProvider], None], *, timeout: float | None = 30
    ) -> p.GitProvider:
        "Fetch, edit with a synchronous callback, and write once under one deadline.\n\nPreserve metadata/resource version. Callback exceptions abort the write;\nconflicts are not retried. In the blocking client the callback runs on\nits event-loop thread, so it must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(ref, mutate, timeout=timeout))

    def update(self, resource: p.GitProvider, *, timeout: float | None = 30) -> p.GitProvider:
        "Replace a complete fetched resource once, preserving its metadata; no automatic retry."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def create(
        self, name: str, spec: p.GitProviderSpec, *, timeout: float | None = 30
    ) -> p.GitProvider:
        "Create a GitProvider using a copied generated spec. OAuth client secrets reference Space Secrets."
        return self._portal.invoke(lambda: self._async.create(name, spec, timeout=timeout))

    def create_oauth(
        self,
        name: str,
        provider: Literal["github", "gitlab"],
        *,
        client_id: str,
        client_secret: str,
        scopes: tuple[str, ...] = (),
        timeout: float | None = 30,
    ) -> p.GitProvider:
        "Create GitHub/GitLab OAuth integration. client_secret is a Space Secret name, not its value."
        return self._portal.invoke(
            lambda: self._async.create_oauth(
                name,
                provider,
                client_id=client_id,
                client_secret=client_secret,
                scopes=scopes,
                timeout=timeout,
            )
        )

    def create_oauth2(
        self,
        name: str,
        *,
        client_id: str,
        client_secret: str,
        auth_url: str,
        token_url: str,
        scopes: tuple[str, ...],
        timeout: float | None = 30,
    ) -> p.GitProvider:
        "Create a generic/self-hosted OAuth2 provider; client_secret names a Space Secret.\n\nauth_url/token_url are the provider endpoints. At least one nonempty\nscope is required. The Cluster validates endpoint and provider policy."
        return self._portal.invoke(
            lambda: self._async.create_oauth2(
                name,
                client_id=client_id,
                client_secret=client_secret,
                auth_url=auth_url,
                token_url=token_url,
                scopes=scopes,
                timeout=timeout,
            )
        )


class Memberships(_Facade[AsyncMemberships]):
    "Membership API. Names may be qualified with their Space; Ref(uid=...) uses immutable IDs."

    def get(self, ref: Reference, *, timeout: float | None = 30) -> p.Membership:
        "Fetch by name or immutable UID; the server enforces access permissions."
        return self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete the resource; ownership and lifecycle restrictions are enforced by the server."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[p.Membership]:
        "Fetch one zero-based page. page_size=0 uses the server default."
        return self._portal.invoke(
            lambda: self._async.list(
                space=space,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[p.Membership]:
        "Iterate lazily from page; breaking stops fetching. timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(
                    space=space,
                    page=page,
                    page_size=page_size,
                    order_by=order_by,
                    descending=descending,
                    timeout=timeout,
                )
            ),
        )

    def modify(
        self, ref: Reference, mutate: Callable[[p.Membership], None], *, timeout: float | None = 30
    ) -> p.Membership:
        "Fetch, edit with a synchronous callback, and write once under one deadline.\n\nPreserve metadata/resource version. Callback exceptions abort the write;\nconflicts are not retried. In the blocking client the callback runs on\nits event-loop thread, so it must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(ref, mutate, timeout=timeout))

    def update(self, resource: p.Membership, *, timeout: float | None = 30) -> p.Membership:
        "Replace a complete fetched resource once, preserving its metadata; no automatic retry."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def add(
        self,
        space: Reference,
        *,
        email: str | None = None,
        user: Reference | None = None,
        role: Role = "user",
        timeout: float | None = 30,
    ) -> p.Membership:
        "Add an existing Cluster user to an organization Space; select exactly one of email or user."
        return self._portal.invoke(
            lambda: self._async.add(space, email=email, user=user, role=role, timeout=timeout)
        )

    def mine(self, space: Reference, *, timeout: float | None = 30) -> p.Membership:
        "Fetch the calling user's membership in a Space."
        return self._portal.invoke(lambda: self._async.mine(space, timeout=timeout))

    def set_role(self, ref: Reference, role: Role, *, timeout: float | None = 30) -> p.Membership:
        "Update a membership's role with a single read and write; no conflict retries."
        return self._portal.invoke(lambda: self._async.set_role(ref, role, timeout=timeout))


class Regions(_Facade[AsyncRegions]):
    "Read-only regions capable of hosting Cordium workspaces."

    def list(
        self, *, page: int = 0, page_size: int = 0, timeout: float | None = 30
    ) -> Page[p.Region]:
        "Fetch one page of regions; page numbers start at zero."
        return self._portal.invoke(
            lambda: self._async.list(page=page, page_size=page_size, timeout=timeout)
        )

    def all(
        self, *, page: int = 0, page_size: int = 100, timeout: float | None = 30
    ) -> Stream[p.Region]:
        "Iterate region pages lazily; timeout applies per page."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.all(page=page, page_size=page_size, timeout=timeout)
            ),
        )


class UserConfig(_Facade[AsyncUserConfig]):
    "The caller's environment, tasks, dotfiles and region preferences."

    def get(self, *, timeout: float | None = 30) -> p.UserConfig:
        "Fetch the caller's complete configuration."
        return self._portal.invoke(lambda: self._async.get(timeout=timeout))

    def update(self, resource: p.UserConfig, *, timeout: float | None = 30) -> p.UserConfig:
        "Replace a complete fetched configuration. Preserve its metadata and resource version."
        return self._portal.invoke(lambda: self._async.update(resource, timeout=timeout))

    def modify(
        self, mutate: Callable[[p.UserConfig], None], *, timeout: float | None = 30
    ) -> p.UserConfig:
        "Fetch, edit with a synchronous callback and write once, preserving metadata.\n\nCallback exceptions abort the write; neither callbacks nor conflicts are\nretried. Blocking-client callbacks must not call blocking SDK methods."
        return self._portal.invoke(lambda: self._async.modify(mutate, timeout=timeout))

    def set_preferred_region(self, region: str, *, timeout: float | None = 30) -> p.UserConfig:
        "Set the preferred placement region name; an empty string clears the preference."
        return self._portal.invoke(
            lambda: self._async.set_preferred_region(region, timeout=timeout)
        )

    def set_dotfiles(
        self, url: str, *, branch: str = "", timeout: float | None = 30
    ) -> p.UserConfig:
        "Configure the dotfiles repository and install scripts run during PREPARING.\n\nEmpty branch uses the repository default. Use modify() for authentication\noptions of private repositories. This replaces the dotfiles configuration."
        return self._portal.invoke(
            lambda: self._async.set_dotfiles(url, branch=branch, timeout=timeout)
        )


class Management(_Facade[AsyncManagement]):
    "Administrative configuration; requires Cluster administrator privileges."

    def get_cluster_config(self, *, timeout: float | None = 30) -> p.ClusterConfig:
        "Read the singleton Cluster configuration."
        return self._portal.invoke(lambda: self._async.get_cluster_config(timeout=timeout))

    def update_cluster_config(
        self, resource: p.ClusterConfig, *, timeout: float | None = 30
    ) -> p.ClusterConfig:
        "Replace the complete fetched Cluster configuration once, without conflict retries."
        return self._portal.invoke(
            lambda: self._async.update_cluster_config(resource, timeout=timeout)
        )

    def modify_cluster_config(
        self, mutate: Callable[[p.ClusterConfig], None], *, timeout: float | None = 30
    ) -> p.ClusterConfig:
        "Fetch, edit and write the Cluster configuration once under one deadline.\n\nThe synchronous callback receives the full resource. Keep metadata intact;\nexceptions abort the write and conflicts are not retried."
        return self._portal.invoke(
            lambda: self._async.modify_cluster_config(mutate, timeout=timeout)
        )


class Files(_Facade[AsyncFiles]):
    "File operations requiring POSIX sh, cat, head, base64, mkdir and rm remotely.\n\nTransfers use fixed-length base64 input because exec cannot signal stdin EOF.\nLocal downloads are atomic; remote writes may leave a partial file on failure.\nPaths are literal and never expanded by the shell (including ~ and $HOME).\nEvery helper defaults to a five-minute timeout."

    def read_bytes(
        self,
        path: str,
        *,
        max_bytes: int = 64 * 1024 * 1024,
        root: bool = False,
        timeout: float | None = 300,
    ) -> bytes:
        "Read a binary file, raising RESOURCE_EXHAUSTED instead of silently truncating."
        return self._portal.invoke(
            lambda: self._async.read_bytes(path, max_bytes=max_bytes, root=root, timeout=timeout)
        )

    def read_text(
        self,
        path: str,
        *,
        encoding: str = "utf-8",
        errors: str = "strict",
        max_bytes: int = 64 * 1024 * 1024,
        root: bool = False,
        timeout: float | None = 300,
    ) -> str:
        "Read and decode a bounded file; invalid text raises UnicodeDecodeError by default."
        return self._portal.invoke(
            lambda: self._async.read_text(
                path,
                encoding=encoding,
                errors=errors,
                max_bytes=max_bytes,
                root=root,
                timeout=timeout,
            )
        )

    def write_bytes(
        self, path: str, data: bytes, *, root: bool = False, timeout: float | None = 300
    ) -> None:
        "Create or truncate a remote file with exact bytes, creating parent directories."
        self._portal.invoke(lambda: self._async.write_bytes(path, data, root=root, timeout=timeout))

    def write_text(
        self,
        path: str,
        text: str,
        *,
        encoding: str = "utf-8",
        errors: str = "strict",
        root: bool = False,
        timeout: float | None = 300,
    ) -> None:
        "Encode text and create or truncate a remote file."
        self._portal.invoke(
            lambda: self._async.write_text(
                path, text, encoding=encoding, errors=errors, root=root, timeout=timeout
            )
        )

    def upload(
        self,
        local_path: str | Path,
        remote_path: str,
        *,
        root: bool = False,
        timeout: float | None = 300,
    ) -> None:
        "Stream a local file with bounded memory. Mutation of its size aborts the transfer."
        self._portal.invoke(
            lambda: self._async.upload(local_path, remote_path, root=root, timeout=timeout)
        )

    def download(
        self,
        remote_path: str,
        local_path: str | Path,
        *,
        root: bool = False,
        timeout: float | None = 300,
    ) -> Path:
        "Stream into a private temporary file and atomically replace the local destination.\n\nA failed transfer preserves an existing destination. Missing parent directories\nare created. The new file has mode 0600 on POSIX; remote permissions are not copied."
        return self._portal.invoke(
            lambda: self._async.download(remote_path, local_path, root=root, timeout=timeout)
        )

    def mkdir(
        self, path: str, *, parents: bool = True, root: bool = False, timeout: float | None = 300
    ) -> None:
        "Create a directory, optionally creating its parents."
        self._portal.invoke(
            lambda: self._async.mkdir(path, parents=parents, root=root, timeout=timeout)
        )

    def remove(
        self,
        path: str,
        *,
        recursive: bool = False,
        missing_ok: bool = False,
        root: bool = False,
        timeout: float | None = 300,
    ) -> None:
        "Remove a literal file/path. Directory recursion must be requested explicitly."
        self._portal.invoke(
            lambda: self._async.remove(
                path, recursive=recursive, missing_ok=missing_ok, root=root, timeout=timeout
            )
        )


class Terminals(_Facade[AsyncTerminals]):
    "Create, list and attach to persistent terminals in one workspace."

    def create(self, *, cols: int = 80, rows: int = 24, timeout: float | None = 30) -> Terminal:
        "Create a PTY shell; its event subscription starts lazily on iteration."
        return Terminal(
            self._portal,
            self._portal.invoke(lambda: self._async.create(cols=cols, rows=rows, timeout=timeout)),
        )

    def list(self, *, timeout: float | None = 30) -> tuple[str, ...]:
        "Return IDs of this workspace's open terminals."
        return self._portal.invoke(lambda: self._async.list(timeout=timeout))

    def attach(
        self, id: str, *, timeout: float | None = None, max_buffer_bytes: int = 8 * 1024 * 1024
    ) -> Terminal:
        "Create a handle to an existing terminal; timeout bounds its event subscription."
        return Terminal(
            self._portal,
            self._portal.invoke(
                lambda: self._async.attach(id, timeout=timeout, max_buffer_bytes=max_buffer_bytes)
            ),
        )

    def remove(self, id: str, *, timeout: float | None = 30) -> None:
        "Terminate the remote shell identified by id."
        self._portal.invoke(lambda: self._async.remove(id, timeout=timeout))


class Terminal(_Facade[AsyncTerminal]):
    "Persistent terminal. Context exit detaches; remove() terminates the remote shell."

    @property
    def id(self) -> str:
        "Terminal identifier assigned by the server."
        return self._portal.invoke(lambda: self._async.id)

    @property
    def events(self) -> Stream[TerminalEvent]:
        "Single-consumer stream of binary output, resize and close events."
        return Stream(self._portal, self._portal.invoke(lambda: self._async.events))

    def write(self, data: str | bytes, *, timeout: float | None = 30) -> None:
        "Write UTF-8 text or bytes to the PTY input."
        self._portal.invoke(lambda: self._async.write(data, timeout=timeout))

    def resize(self, cols: int, rows: int, *, timeout: float | None = 30) -> None:
        "Change window dimensions; both dimensions must be positive integers."
        self._portal.invoke(lambda: self._async.resize(cols, rows, timeout=timeout))

    def remove(self, *, timeout: float | None = 30) -> None:
        "Terminate the remote shell, then detach locally even if the request fails."
        self._portal.invoke(lambda: self._async.remove(timeout=timeout))

    def close(self) -> None:
        "Detach this listener, preserving the remote shell for later attachment."
        self._portal.release(self._async.aclose)

    def __enter__(self) -> Terminal:
        """Enter the owned async context and return this blocking handle."""
        self._portal.invoke(self._async.__aenter__)
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Release local resources on context exit."""
        self.close()


class Workspaces(_Facade[AsyncWorkspaces]):
    "Create and find workspace handles. New workspaces are stopped until started."

    def create(
        self, *, timeout: float | None = 30, **options: Unpack[WorkspaceOptions]
    ) -> Workspace:
        "Create a stopped workspace with a server-assigned name.\n\nSelect template or snapshot with Ref or name. Convenience options override\nthe corresponding fields of a deep-copied generated spec. No start is implicit."
        return Workspace(
            self._portal,
            self._portal.invoke(lambda: self._async.create(timeout=timeout, **options)),
        )

    def run(
        self,
        *,
        timeout: float | None = 300,
        poll_interval: float = 1,
        region: Reference | None = None,
        **options: Unpack[WorkspaceOptions],
    ) -> Workspace:
        "Create, start and wait for RUNNING under one total deadline.\n\nFailures leave the workspace in place for diagnosis; no implicit deletion.\nA CordiumError raised after creation keeps its code and carries the\nworkspace's last fetched state in ``error.workspace``. Region selects\nplacement for this run. poll_interval is in seconds."
        return Workspace(
            self._portal,
            self._portal.invoke(
                lambda: self._async.run(
                    timeout=timeout, poll_interval=poll_interval, region=region, **options
                )
            ),
        )

    def get(self, ref: Reference, *, timeout: float | None = 30) -> Workspace:
        "Fetch an existing workspace by name or immutable UID."
        return Workspace(
            self._portal, self._portal.invoke(lambda: self._async.get(ref, timeout=timeout))
        )

    def delete(self, ref: Reference, *, timeout: float | None = 30) -> None:
        "Delete a workspace. The server enforces lifecycle restrictions."
        self._portal.invoke(lambda: self._async.delete(ref, timeout=timeout))

    def list(
        self,
        *,
        space: Reference | None = None,
        template: Reference | None = None,
        page: int = 0,
        page_size: int = 0,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Page[Workspace]:
        "Fetch a zero-based page of the caller's workspaces; filters are exclusive."
        value = self._portal.invoke(
            lambda: self._async.list(
                space=space,
                template=template,
                page=page,
                page_size=page_size,
                order_by=order_by,
                descending=descending,
                timeout=timeout,
            )
        )
        return Page(
            tuple(Workspace(self._portal, item) for item in value.items),
            value.page,
            value.page_size,
            value.total_count,
            value.has_more,
        )

    def all(
        self,
        *,
        space: Reference | None = None,
        template: Reference | None = None,
        page: int = 0,
        page_size: int = 100,
        order_by: Literal["name", "created_at"] | None = None,
        descending: bool = False,
        timeout: float | None = 30,
    ) -> Stream[Workspace]:
        "Lazily fetch workspaces. timeout applies to each page request."
        return Stream(
            self._portal,
            _workspace_items(
                self._portal,
                self._portal.invoke(
                    lambda: self._async.all(
                        space=space,
                        template=template,
                        page=page,
                        page_size=page_size,
                        order_by=order_by,
                        descending=descending,
                        timeout=timeout,
                    )
                ),
            ),
        )

    def update(self, workspace: p.Workspace, *, timeout: float | None = 30) -> Workspace:
        "Replace a fetched protobuf resource once; no retry of version conflicts."
        return Workspace(
            self._portal,
            self._portal.invoke(lambda: self._async.update(workspace, timeout=timeout)),
        )

    def watch(
        self,
        ref: Reference | None = None,
        *,
        timeout: float | None = None,
        max_buffer_bytes: int = 8 * 1024 * 1024,
    ) -> Stream[WorkspaceEvent]:
        "Subscribe to future create/update/delete events; no initial snapshot or reconnect.\n\nUse an context manager when stopping iteration early. Update events\ncarry the previous resource when the server reports it."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.watch(ref, timeout=timeout, max_buffer_bytes=max_buffer_bytes)
            ),
        )


class Workspace(_Facade[AsyncWorkspace]):
    "Workspace handle with an isolated cache; refresh/lifecycle methods update it.\n\nProperties never perform network calls. Returned protobuf objects are deep copies.\nKeep the parent client open while using a handle. Closing it never deletes workspaces."

    @property
    def proto(self) -> p.Workspace:
        "Deep copy of the last resource returned by the Cluster."
        return self._portal.invoke(lambda: self._async.proto)

    @property
    def name(self) -> str:
        "Server-assigned name."
        return self._portal.invoke(lambda: self._async.name)

    @property
    def uid(self) -> str:
        "Immutable Cluster-wide identifier."
        return self._portal.invoke(lambda: self._async.uid)

    @property
    def display_name(self) -> str:
        "Optional human-readable label."
        return self._portal.invoke(lambda: self._async.display_name)

    @property
    def created_at(self) -> datetime:
        "Creation timestamp, represented as a timezone-aware datetime."
        return self._portal.invoke(lambda: self._async.created_at)

    @property
    def is_ephemeral(self) -> bool:
        "Whether storage is discarded when the workspace stops."
        return self._portal.invoke(lambda: self._async.is_ephemeral)

    @property
    def space_name(self) -> str:
        "Name of the Space the workspace belongs to."
        return self._portal.invoke(lambda: self._async.space_name)

    @property
    def template_name(self) -> str:
        "Name of the Template the workspace was created from, or empty."
        return self._portal.invoke(lambda: self._async.template_name)

    @property
    def region_name(self) -> str:
        "Name of the Region currently hosting the workspace, or empty."
        return self._portal.invoke(lambda: self._async.region_name)

    @property
    def failure(self) -> p.WorkspaceStatusFailure | None:
        "Deep copy of the current or latest run's failure, if any."
        return self._portal.invoke(lambda: self._async.failure)

    @property
    def limit(self) -> p.WorkspaceSpecLimit:
        "Deep copy of the effective compute limits resolved by the Cluster."
        return self._portal.invoke(lambda: self._async.limit)

    @property
    def state(self) -> State:
        "Last observed lifecycle state."
        return cast(State, self._portal.invoke(lambda: self._async.state))

    @property
    def is_ready(self) -> bool:
        "Whether exec/terminals are available (PREPARING or RUNNING)."
        return self._portal.invoke(lambda: self._async.is_ready)

    @property
    def is_running(self) -> bool:
        "Whether initialization has completed."
        return self._portal.invoke(lambda: self._async.is_running)

    @property
    def is_starting(self) -> bool:
        "Whether provisioning is in progress before PREPARING."
        return self._portal.invoke(lambda: self._async.is_starting)

    @property
    def is_stopping(self) -> bool:
        "Whether a stop is in progress."
        return self._portal.invoke(lambda: self._async.is_stopping)

    @property
    def is_stopped(self) -> bool:
        "Whether the workspace is stopped."
        return self._portal.invoke(lambda: self._async.is_stopped)

    @property
    def hostname(self) -> str:
        "Public hostname, or empty when stopped."
        return self._portal.invoke(lambda: self._async.hostname)

    @property
    def url(self) -> str:
        "HTTPS URL of the default application, or empty when stopped."
        return self._portal.invoke(lambda: self._async.url)

    @property
    def spec(self) -> p.WorkspaceSpec:
        "Deep copy of the persisted spec."
        return self._portal.invoke(lambda: self._async.spec)

    @property
    def status(self) -> p.WorkspaceStatus:
        "Deep copy of status, including effective limits, run, sharing and failure details."
        return self._portal.invoke(lambda: self._async.status)

    @property
    def applications(self) -> tuple[p.WorkspaceSpecApplication, ...]:
        "Declared named application ports, copied from the cache."
        return self._portal.invoke(lambda: self._async.applications)

    @property
    def files(self) -> Files:
        "Binary-safe file operations implemented through exec."
        return Files(self._portal, self._portal.invoke(lambda: self._async.files))

    @property
    def terminals(self) -> Terminals:
        "Persistent PTY shells; detaching does not terminate them."
        return Terminals(self._portal, self._portal.invoke(lambda: self._async.terminals))

    def app_url(self, name: str) -> str:
        "Application URL using Cordium's underscore routing, or empty when stopped."
        return self._portal.invoke(lambda: self._async.app_url(name))

    def port_url(self, port: int) -> str:
        "HTTPS route to a port from 1 through 65535, or empty when stopped."
        return self._portal.invoke(lambda: self._async.port_url(port))

    def refresh(self, *, timeout: float | None = 30) -> Workspace:
        "Fetch the current resource into this handle and return it."
        return Workspace(
            self._portal, self._portal.invoke(lambda: self._async.refresh(timeout=timeout))
        )

    def modify(
        self, mutate: Callable[[p.Workspace], None], *, timeout: float | None = 30
    ) -> Workspace:
        "Fetch, mutate a copied resource and update once, refreshing this handle.\n\nThe callback is synchronous; exceptions abort the write. Conflicts are\nsurfaced without retrying or repeating callback side effects."
        return Workspace(
            self._portal, self._portal.invoke(lambda: self._async.modify(mutate, timeout=timeout))
        )

    def start(
        self,
        *,
        vars: Mapping[str, str] | None = None,
        region: Reference | None = None,
        timeout: float | None = 30,
    ) -> Workspace:
        "Request an asynchronous start, then refresh; vars/region apply only to this run.\n\nStarting a workspace that is already starting or running is a no-op."
        return Workspace(
            self._portal,
            self._portal.invoke(
                lambda: self._async.start(vars=vars, region=region, timeout=timeout)
            ),
        )

    def stop(self, *, timeout: float | None = 30) -> Workspace:
        "Request an asynchronous stop and refresh. Ephemeral storage is discarded."
        return Workspace(
            self._portal, self._portal.invoke(lambda: self._async.stop(timeout=timeout))
        )

    def snapshot(self, name: str, *, timeout: float | None = 30) -> p.WorkspaceSnapshot:
        "Request a storage snapshot; use client.snapshots.wait_until_ready before restoring.\n\nRequires persistent storage. A running workspace snapshot is crash-consistent."
        return self._portal.invoke(lambda: self._async.snapshot(name, timeout=timeout))

    def delete(self, *, timeout: float | None = 30) -> None:
        "Delete this workspace; the server enforces lifecycle restrictions."
        self._portal.invoke(lambda: self._async.delete(timeout=timeout))

    def wait_until_running(
        self, *, timeout: float | None = 300, poll_interval: float = 1
    ) -> Workspace:
        "Wait for RUNNING, failing promptly on failure or a stopped/stopping run."
        return Workspace(
            self._portal,
            self._portal.invoke(
                lambda: self._async.wait_until_running(timeout=timeout, poll_interval=poll_interval)
            ),
        )

    def wait_until_ready(
        self, *, timeout: float | None = 300, poll_interval: float = 1
    ) -> Workspace:
        "Wait until PREPARING or RUNNING accepts commands; setup may still be running."
        return Workspace(
            self._portal,
            self._portal.invoke(
                lambda: self._async.wait_until_ready(timeout=timeout, poll_interval=poll_interval)
            ),
        )

    def wait_until_stopped(
        self, *, timeout: float | None = 300, poll_interval: float = 1
    ) -> Workspace:
        "Wait for STOPPED; raise WorkspaceFailureError if the run that stopped had failed."
        return Workspace(
            self._portal,
            self._portal.invoke(
                lambda: self._async.wait_until_stopped(timeout=timeout, poll_interval=poll_interval)
            ),
        )

    def exec(
        self,
        command: str | Sequence[str],
        *,
        cwd: str = "",
        env: Mapping[str, str] | None = None,
        root: bool = False,
        stdin: str | bytes | None = None,
        check: bool = False,
        timeout: float | None = None,
        max_capture_bytes: int = 1024 * 1024,
    ) -> ExecResult:
        "Run a shell command or safely quoted argv and collect bounded output.\n\nA nonzero exit is returned in the result; check=True raises ExecError instead. stdin is initial input, not\nan EOF signal: Cordium's protocol cannot half-close stdin. Commands that\nread until EOF need explicit framing (e.g. head -c). Timeout cancels exec."
        return self._portal.invoke(
            lambda: self._async.exec(
                command,
                cwd=cwd,
                env=env,
                root=root,
                stdin=stdin,
                check=check,
                timeout=timeout,
                max_capture_bytes=max_capture_bytes,
            )
        )

    def exec_stream(
        self,
        command: str | Sequence[str],
        *,
        cwd: str = "",
        env: Mapping[str, str] | None = None,
        root: bool = False,
        stdin: str | bytes | None = None,
        interactive: bool = True,
        check: bool = False,
        timeout: float | None = None,
        max_capture_bytes: int = 1024 * 1024,
        max_buffer_bytes: int = 8 * 1024 * 1024,
        kill_grace: float = 10,
    ) -> ExecSession:
        "Start a command; iterate binary stdout/stderr, write input, kill or await its result.\n\nUse ``with workspace.exec_stream(...)`` to close on early exit.\nA full stream queue pauses reading output until it drains; capture truncation\nis reported in ExecResult. A killed command that reports no exit within\nkill_grace seconds ends with exit code -1."
        return ExecSession(
            self._portal,
            self._portal.invoke(
                lambda: self._async.exec_stream(
                    command,
                    cwd=cwd,
                    env=env,
                    root=root,
                    stdin=stdin,
                    interactive=interactive,
                    check=check,
                    timeout=timeout,
                    max_capture_bytes=max_capture_bytes,
                    max_buffer_bytes=max_buffer_bytes,
                    kill_grace=kill_grace,
                )
            ),
        )

    def logs(
        self, *, timeout: float | None = None, max_buffer_bytes: int = 8 * 1024 * 1024
    ) -> Stream[LogEntry]:
        "Stream initialization logs: repository cloning, image pulls and builds, and tasks."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.logs(timeout=timeout, max_buffer_bytes=max_buffer_bytes)
            ),
        )

    def watch(
        self, *, timeout: float | None = None, max_buffer_bytes: int = 8 * 1024 * 1024
    ) -> Stream[WorkspaceEvent]:
        "Subscribe to this workspace's events; does not implicitly update this handle."
        return Stream(
            self._portal,
            self._portal.invoke(
                lambda: self._async.watch(timeout=timeout, max_buffer_bytes=max_buffer_bytes)
            ),
        )

    def share_port(
        self,
        application: str,
        *,
        mode: Literal["members", "all"] = "members",
        timeout: float | None = 30,
    ) -> Workspace:
        "Share a named application with Space members or all authenticated Cluster users."
        return Workspace(
            self._portal,
            self._portal.invoke(
                lambda: self._async.share_port(application, mode=mode, timeout=timeout)
            ),
        )

    def unshare_port(self, application: str, *, timeout: float | None = 30) -> Workspace:
        "Revoke sharing of a named application and refresh the cache."
        return Workspace(
            self._portal,
            self._portal.invoke(lambda: self._async.unshare_port(application, timeout=timeout)),
        )


class ExecSession(_Facade[AsyncExecSession]):
    "Running command with ordered async output, write(), kill(), wait(), and close().\n\nUse an async context manager to cancel on early iteration exit. wait() drains\noutput if iteration has not started. Captures and streaming queues have separate\nlimits; a full streaming queue pauses reading the command's output until it drains."

    def ready(self) -> ExecSession:
        "Wait until the initial command request has been sent."
        return ExecSession(self._portal, self._portal.invoke(lambda: self._async.ready()))

    def write(self, data: str | bytes) -> None:
        "Write stdin with serialized 32-KiB messages. This never sends EOF."
        self._portal.invoke(lambda: self._async.write(data))

    def kill(self) -> None:
        "Terminate the remote process group; the server normally reports exit code -1.\n\nA command whose exit is not reported within kill_grace seconds ends the session\non its own with exit code -1 and killed set."
        self._portal.invoke(lambda: self._async.kill())

    def wait(self) -> ExecResult:
        "Await completion. Before iteration starts, selects drain-only consumption."
        return self._portal.invoke(lambda: self._async.wait())

    def close(self) -> None:
        "Cancel execution and release local buffers. Does not delete the workspace."
        self._portal.release(self._async.aclose)

    def __enter__(self) -> ExecSession:
        """Enter the owned async context and return this blocking handle."""
        self._portal.invoke(self._async.__aenter__)
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Release local resources on context exit."""
        self.close()

    def __iter__(self) -> Iterator[ExecOutput]:
        """Iterate ordered binary output; use the session context manager for early exit."""
        self._portal.invoke(self._async.__aiter__)
        return Stream(self._portal, self._async)


class Cordium(_Facade[AsyncCordium]):
    "Blocking Cordium SDK with one owned event-loop thread; use with.\n\n        Safe for calls from multiple threads. Create a new client after fork.\n        domain selects the Cluster, and RPCs default to octelium-api.<domain>:443.\n        auth defaults to Octelium credential environment variables. TLS verifies\n        peers; use ssl_context_factory for custom CAs. Construction does not contact\n        the Cluster. close() cancels operations and joins the thread.\n"

    def __init__(
        self,
        domain: str | None = None,
        *,
        auth: Credentials | AuthConfig | None = None,
        host: str | None = None,
        port: int = 443,
        ssl_context_factory: Callable[[], ssl.SSLContext] | None = None,
        insecure_tls: bool = False,
        tls_server_name: str = "",
        authorized_http_hosts: Sequence[str] = (),
        allow_insecure_http: bool = False,
    ) -> None:
        portal = Portal()
        try:
            value = portal.invoke(
                lambda: AsyncCordium(
                    domain,
                    auth=auth,
                    host=host,
                    port=port,
                    ssl_context_factory=ssl_context_factory,
                    insecure_tls=insecure_tls,
                    tls_server_name=tls_server_name,
                    authorized_http_hosts=authorized_http_hosts,
                    allow_insecure_http=allow_insecure_http,
                )
            )
        except BaseException:

            async def cleanup() -> None:
                pass

            portal.close(cleanup)
            raise
        super().__init__(portal, value)

    def call(self, operation: Callable[[AsyncCordium], Awaitable[T]]) -> T:
        """Run an advanced async operation on the owned loop, including generated raw RPCs.

        Example: client.call(lambda c: c.raw.main.get_workspace(request, timeout=10)).
        Callbacks must not call blocking methods on this same client.
        """
        return self._portal.invoke(lambda: operation(self._async))

    @property
    def domain(self) -> str:
        "Normalized Cluster domain used for application HTTP authorization."
        return self._portal.invoke(lambda: self._async.domain)

    @property
    def workspaces(self) -> Workspaces:
        "Workspace creation, listing, lifecycle and event subscriptions."
        return Workspaces(self._portal, self._portal.invoke(lambda: self._async.workspaces))

    @property
    def spaces(self) -> Spaces:
        "Personal and organization Spaces."
        return Spaces(self._portal, self._portal.invoke(lambda: self._async.spaces))

    @property
    def templates(self) -> Templates:
        "Reusable configurations and asynchronous image builds."
        return Templates(self._portal, self._portal.invoke(lambda: self._async.templates))

    @property
    def snapshots(self) -> Snapshots:
        "Workspace storage snapshots and readiness waits."
        return Snapshots(self._portal, self._portal.invoke(lambda: self._async.snapshots))

    @property
    def volumes(self) -> Volumes:
        "Persistent attachable volumes and monotonic size growth."
        return Volumes(self._portal, self._portal.invoke(lambda: self._async.volumes))

    @property
    def secrets(self) -> Secrets:
        "Space-scoped write-only Secrets."
        return Secrets(self._portal, self._portal.invoke(lambda: self._async.secrets))

    @property
    def user_secrets(self) -> UserSecrets:
        "Caller-owned Secrets, including Cluster-generated SSH key pairs."
        return UserSecrets(self._portal, self._portal.invoke(lambda: self._async.user_secrets))

    @property
    def git_providers(self) -> GitProviders:
        "Space OAuth providers and advanced generated configurations."
        return GitProviders(self._portal, self._portal.invoke(lambda: self._async.git_providers))

    @property
    def memberships(self) -> Memberships:
        "Space membership invitations and roles."
        return Memberships(self._portal, self._portal.invoke(lambda: self._async.memberships))

    @property
    def regions(self) -> Regions:
        "Available workspace placement regions."
        return Regions(self._portal, self._portal.invoke(lambda: self._async.regions))

    @property
    def user_config(self) -> UserConfig:
        "The authenticated user's Cordium configuration."
        return UserConfig(self._portal, self._portal.invoke(lambda: self._async.user_config))

    @property
    def management(self) -> Management:
        "Cluster administration; server-side permissions apply."
        return Management(self._portal, self._portal.invoke(lambda: self._async.management))

    def access_token(self, *, timeout: float | None = 30) -> str:
        "Obtain a current token, refreshing a managed session if necessary. Treat as a secret."
        return self._portal.invoke(lambda: self._async.access_token(timeout=timeout))

    def request(
        self,
        method: str,
        url: str,
        *,
        headers: Mapping[str, str] | None = None,
        content: str | bytes | None = None,
        json: JsonValue = None,
        timeout: float | None = 30,
        max_response_bytes: int = 16 * 1024 * 1024,
    ) -> httpx.Response:
        "Call a workspace application with current Octelium authentication.\n\nOnly HTTPS Cluster-domain/subdomain destinations and explicitly authorized\nhosts are allowed. Credentials travel in the x-octelium-auth header, leaving\nthe application's own Authorization header alone. Redirects are returned\nwithout following. The response\nbody is buffered up to max_response_bytes; non-2xx statuses are returned,\nso call response.raise_for_status() if desired. timeout covers authentication\nand the full body. HTTP transport failures use code UNAVAILABLE."
        return self._portal.invoke(
            lambda: self._async.request(
                method,
                url,
                headers=headers,
                content=content,
                json=json,
                timeout=timeout,
                max_response_bytes=max_response_bytes,
            )
        )

    def close(self) -> None:
        "Cancel SDK operations and close the owned Octelium client; never stop or delete resources."
        self._portal.close(self._async.aclose)

    def __enter__(self) -> Cordium:
        """Enter the owned async context and return this blocking handle."""
        self._portal.invoke(self._async.__aenter__)
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Release local resources on context exit."""
        self.close()
