# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: apis/protobuf/main/metav1/metav1.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    Dict,
    List,
)

import betterproto


class CommonListOptionsOrderByType(betterproto.Enum):
    TYPE_UNSET = 0
    NAME = 1
    CREATED_AT = 2


class CommonListOptionsOrderByMode(betterproto.Enum):
    MODE_UNSET = 0
    ASC = 1
    DESC = 2


@dataclass(eq=False, repr=False)
class Metadata(betterproto.Message):
    uid: str = betterproto.string_field(1)
    """
    UID is the unique UUID value for the object assigned by the Cluster.
     Read-only.
    """

    name: str = betterproto.string_field(2)
    """
    Name is the name of the object. It must be unique within a certain
     API/Version/Kind tuple.
    """

    created_at: datetime = betterproto.message_field(3)
    """CreatedAt is the timestamp of creation of the object. Read-only."""

    updated_at: datetime = betterproto.message_field(4)
    """
    UpdatedAt is the timestamp of when the object was last updated.
     Read-only.
    """

    display_name: str = betterproto.string_field(5)
    """
    DisplayName is the name that can be shown publicly for the object. Doesn't
     need to be unique.
    """

    description: str = betterproto.string_field(6)
    """
    Description is used to describe the object in a short sentence. Maximum
     characters are 1000.
    """

    labels: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """Labels is a map of string keys and values to organize objects."""

    tags: List[str] = betterproto.string_field(8)
    """Tags is an optional array of tags that classify the Resource."""

    annotations: Dict[str, str] = betterproto.map_field(
        9, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """
    Labels is a map of string keys and values that can be used to store
     metadata about the object.
    """

    pic_url: str = betterproto.string_field(10)
    """PicURL is the Picture URL of the resource."""

    resource_version: str = betterproto.string_field(11)
    """
    ResourceVersion is a unique ID that represent the current version of the
     resource object. Used by the Cluster to detect updates.
    """

    last_resource_version: str = betterproto.string_field(12)
    """
    LastResourceVersion is the ResourceVersion of the last update of the
     Resource.
    """

    actor_ref: "ObjectReference" = betterproto.message_field(13)
    """
    ActorRef is the object reference to the Actor resource, typically a
     Session, who is responsible for the current resource change. If ActorRef is
     not set, then the current change of the resource was done by the Cluster
    """

    actor_operation: str = betterproto.string_field(14)
    """
    ActorOperation is the gRPC full method triggered by the actorRef to modify
     the Resource
    """

    is_system: bool = betterproto.bool_field(15)
    """
    IsSystem means that the resource is created by the Cluster and it cannot be
     managed by the administrators. Read-only.
    """

    spec_labels: Dict[str, str] = betterproto.map_field(
        16, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """
    SpecLabels is map used internally by the Cluster for quick searches among
     lists of objects. Read-only.
    """

    is_user_hidden: bool = betterproto.bool_field(17)
    """
    IsUserHidden means that the resource object is hidden from ordinary Users
     and should not be exposed via the User APIs.
    """

    is_system_hidden: bool = betterproto.bool_field(18)
    """
    IsSystemHidden means that the resource object is hidden by the Cluster and
     should not be exposed via the APIs.
    """

    system_labels: Dict[str, str] = betterproto.map_field(
        19, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """
    SystemLabels is a similar map to specLabels. Used only by the Cluster.
    """


@dataclass(eq=False, repr=False)
class ObjectReference(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    """APIVersion is the API version of the reference resource"""

    kind: str = betterproto.string_field(2)
    """Kind is the resource kind. A kind is unique per an APIVersion."""

    uid: str = betterproto.string_field(3)
    """
    UID is the resource object UID. A UID is unique across the entire Cluster.
    """

    name: str = betterproto.string_field(4)
    """
    Name is the resource object name. A name is unique per a certain kind.
    """

    resource_version: str = betterproto.string_field(5)
    """ResourceVersion is the resourceVersion of the resource."""


@dataclass(eq=False, repr=False)
class Duration(betterproto.Message):
    milliseconds: int = betterproto.uint32_field(1, group="type")
    """Milliseconds is the duration set in milliseconds"""

    seconds: int = betterproto.uint32_field(2, group="type")
    """Seconds is the duration set in seconds"""

    minutes: int = betterproto.uint32_field(3, group="type")
    """Minutes is the duration set in minutes"""

    hours: int = betterproto.uint32_field(4, group="type")
    """Hours is the duration set in hours"""

    days: int = betterproto.uint32_field(5, group="type")
    """Days is the duration set in days"""

    weeks: int = betterproto.uint32_field(6, group="type")
    """Weeks is the duration set in weeks"""

    months: int = betterproto.uint32_field(7, group="type")
    """Months is the duration set in months"""


@dataclass(eq=False, repr=False)
class DeleteOptions(betterproto.Message):
    uid: str = betterproto.string_field(1)
    """UID is the objet's UID."""

    name: str = betterproto.string_field(2)
    """
    Name is the object name that needs to be deleted. Either the name or the
     UID must be used.
    """


@dataclass(eq=False, repr=False)
class GetOptions(betterproto.Message):
    uid: str = betterproto.string_field(1)
    """UID is the object's UID"""

    name: str = betterproto.string_field(2)
    """Name is the object's name"""


@dataclass(eq=False, repr=False)
class OperationResult(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DualStackIp(betterproto.Message):
    ipv4: str = betterproto.string_field(1)
    """IPv4 is the IPv4 address."""

    ipv6: str = betterproto.string_field(2)
    """IPv6 is the IPv6 address."""


@dataclass(eq=False, repr=False)
class DualStackNetwork(betterproto.Message):
    v4: str = betterproto.string_field(1)
    """
    V4 is the IPv4 network address represented as CIDR notation IP address
     and prefix length (e.g. `192.0.2.0/24`).
    """

    v6: str = betterproto.string_field(2)
    """
    V6 is the IPv6 network address represented as CIDR notation IP address
     and prefix length (e.g. `2001:db8::/32`).
    """


@dataclass(eq=False, repr=False)
class ListResponseMeta(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    """Page is the page number. Starts with zero."""

    items_per_page: int = betterproto.uint32_field(2)
    """ItemsPerPage is number of items per page."""

    total_count: int = betterproto.uint32_field(3)
    """TotalCount is the total count of items that can be obtained."""

    has_more: bool = betterproto.bool_field(4)
    """HasMore shows whether there a next page is available"""


@dataclass(eq=False, repr=False)
class LogMetadata(betterproto.Message):
    id: str = betterproto.string_field(1)
    """ID is the unique ID for the log entry"""

    created_at: datetime = betterproto.message_field(2)
    """CreatedAt is the timestamp of creation."""

    actor_ref: "ObjectReference" = betterproto.message_field(3)
    """
    Actor is the actor whose action triggered the log entry (i.e. the User,
     their Session and Device if available)
    """

    target_ref: "ObjectReference" = betterproto.message_field(4)
    """
    Target is the target of the action that triggered the log entry (e.g. the
     Service and its Namespace in the case of a SERVICE log entry)
    """


@dataclass(eq=False, repr=False)
class CommonListOptions(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    """Page is the page number, starts at zero."""

    items_per_page: int = betterproto.uint32_field(2)
    """ItemsPerPage is the items per page"""

    order_by: "CommonListOptionsOrderBy" = betterproto.message_field(3)
    """OrderBy orders the list"""


@dataclass(eq=False, repr=False)
class CommonListOptionsOrderBy(betterproto.Message):
    type: "CommonListOptionsOrderByType" = betterproto.enum_field(1)
    mode: "CommonListOptionsOrderByMode" = betterproto.enum_field(2)
