# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: apis/protobuf/main/authv1/authv1.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ...meta import v1 as __meta_v1__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ClientLoginRequestApiVersion(betterproto.Enum):
    UNKNOWN_VERSION = 0
    V1 = 1
    V2 = 2
    """
    Clients keep sending V1 until Clusters that reject unknown API versions
     have aged out. A V1 request carrying a codeChallenge is normalized to V2
     by the Cluster.
    """


class RegisterDeviceBeginRequestInfoOsType(betterproto.Enum):
    OS_TYPE_UNKNOWN = 0
    LINUX = 1
    WINDOWS = 2
    MAC = 3
    ANDROID = 4
    IOS = 5


class TokenT0ContentType(betterproto.Enum):
    TYPE_UNKNOWN = 0
    ACCESS_TOKEN = 1
    REFRESH_TOKEN = 2
    CREDENTIAL = 3


class AuthenticatorStatusType(betterproto.Enum):
    TYPE_UNKNOWN = 0
    FIDO = 1
    TOTP = 2
    TPM = 3


@dataclass(eq=False, repr=False)
class SessionToken(betterproto.Message):
    access_token: str = betterproto.string_field(1)
    refresh_token: str = betterproto.string_field(2)
    expires_in: int = betterproto.int64_field(3)
    refresh_token_expires_in: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class ClientLoginRequest(betterproto.Message):
    api_version: "ClientLoginRequestApiVersion" = betterproto.enum_field(1)
    callback_port: int = betterproto.uint32_field(2)
    callback_suffix: str = betterproto.string_field(3)
    code_challenge: bytes = betterproto.bytes_field(4)
    """
    CodeChallenge is the SHA256 digest of the 32 random bytes of the code
     verifier. This is S256 over the raw verifier bytes, NOT over the base64url
     encoding used by RFC 7636.
    """


@dataclass(eq=False, repr=False)
class ClientLoginResponse(betterproto.Message):
    authentication_token: str = betterproto.string_field(1)
    code_challenge: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class LogoutRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class LogoutResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class RegisterDeviceBeginRequest(betterproto.Message):
    info: "RegisterDeviceBeginRequestInfo" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class RegisterDeviceBeginRequestInfo(betterproto.Message):
    os_type: "RegisterDeviceBeginRequestInfoOsType" = betterproto.enum_field(1)
    hostname: str = betterproto.string_field(2)
    id: str = betterproto.string_field(3)
    serial_number: str = betterproto.string_field(4)
    mac_addresses: List[str] = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class RegisterDeviceBeginResponse(betterproto.Message):
    uid: str = betterproto.string_field(1)
    requests: List["RegisterDeviceBeginResponseRequest"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class RegisterDeviceBeginResponseRequest(betterproto.Message):
    uid: str = betterproto.string_field(1)
    command: "RegisterDeviceBeginResponseRequestCommand" = betterproto.message_field(
        2, group="type"
    )
    file: "RegisterDeviceBeginResponseRequestFile" = betterproto.message_field(
        3, group="type"
    )


@dataclass(eq=False, repr=False)
class RegisterDeviceBeginResponseRequestCommand(betterproto.Message):
    command: str = betterproto.string_field(1)
    args: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class RegisterDeviceBeginResponseRequestFile(betterproto.Message):
    path: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RegisterDeviceFinishRequest(betterproto.Message):
    uid: str = betterproto.string_field(1)
    responses: List["RegisterDeviceFinishRequestResponse"] = betterproto.message_field(
        2
    )


@dataclass(eq=False, repr=False)
class RegisterDeviceFinishRequestResponse(betterproto.Message):
    uid: str = betterproto.string_field(1)
    command: "RegisterDeviceFinishRequestResponseCommand" = betterproto.message_field(
        2, group="type"
    )
    file: "RegisterDeviceFinishRequestResponseFile" = betterproto.message_field(
        3, group="type"
    )


@dataclass(eq=False, repr=False)
class RegisterDeviceFinishRequestResponseCommand(betterproto.Message):
    output: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class RegisterDeviceFinishRequestResponseFile(betterproto.Message):
    output: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class RegisterDeviceFinishResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class AuthenticateWithAuthenticationTokenRequest(betterproto.Message):
    authentication_token: str = betterproto.string_field(1)
    scopes: List[str] = betterproto.string_field(2)
    code_verifier: bytes = betterproto.bytes_field(3)
    """
    CodeVerifier is required if and only if the Credential is bound to a code
     challenge. Supplying it for a Credential that is not bound is rejected.
    """


@dataclass(eq=False, repr=False)
class AuthenticateWithAssertionRequest(betterproto.Message):
    identity_provider_ref: "__meta_v1__.ObjectReference" = betterproto.message_field(1)
    assertion: str = betterproto.string_field(2)
    scopes: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class AuthenticateWithRefreshTokenRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class TokenT0(betterproto.Message):
    signature: bytes = betterproto.bytes_field(1)
    content: "TokenT0Content" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class TokenT0Content(betterproto.Message):
    type: "TokenT0ContentType" = betterproto.enum_field(1)
    key_id: bytes = betterproto.bytes_field(2)
    subject: bytes = betterproto.bytes_field(3)
    token_id: bytes = betterproto.bytes_field(4)
    expires_at: datetime = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginRequest(betterproto.Message):
    authenticator_ref: "__meta_v1__.ObjectReference" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginResponse(betterproto.Message):
    challenge_request: "AuthenticateAuthenticatorBeginResponseChallengeRequest" = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginResponseChallengeRequest(betterproto.Message):
    fido: "AuthenticateAuthenticatorBeginResponseChallengeRequestFido" = (
        betterproto.message_field(1, group="type")
    )
    totp: "AuthenticateAuthenticatorBeginResponseChallengeRequestTotp" = (
        betterproto.message_field(2, group="type")
    )
    tpm: "AuthenticateAuthenticatorBeginResponseChallengeRequestTpm" = (
        betterproto.message_field(3, group="type")
    )


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginResponseChallengeRequestFido(betterproto.Message):
    request: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginResponseChallengeRequestTotp(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginResponseChallengeRequestTpm(betterproto.Message):
    encrypted_credential: (
        "AuthenticateAuthenticatorBeginResponseChallengeRequestTpmEncryptedCredential"
    ) = betterproto.message_field(1)
    ak_bytes: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class AuthenticateAuthenticatorBeginResponseChallengeRequestTpmEncryptedCredential(
    betterproto.Message
):
    credential: bytes = betterproto.bytes_field(1)
    secret: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginRequest(betterproto.Message):
    authenticator_ref: "__meta_v1__.ObjectReference" = betterproto.message_field(1)
    pre_challenge: "RegisterAuthenticatorBeginRequestPreChallenge" = (
        betterproto.message_field(2)
    )


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginRequestPreChallenge(betterproto.Message):
    tpm: "RegisterAuthenticatorBeginRequestPreChallengeTpm" = betterproto.message_field(
        1, group="type"
    )


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginRequestPreChallengeTpm(betterproto.Message):
    ak_bytes: bytes = betterproto.bytes_field(1)
    attestation_parameters: (
        "RegisterAuthenticatorBeginRequestPreChallengeTpmAttestationParameters"
    ) = betterproto.message_field(2)
    ek_certificate_der: bytes = betterproto.bytes_field(3, group="ekType")
    ek_public_key: bytes = betterproto.bytes_field(4, group="ekType")
    ek_certificate_intermediates_der: List[bytes] = betterproto.bytes_field(5)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginRequestPreChallengeTpmAttestationParameters(
    betterproto.Message
):
    public: bytes = betterproto.bytes_field(1)
    create_data: bytes = betterproto.bytes_field(2)
    create_attestation: bytes = betterproto.bytes_field(3)
    create_signature: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginResponse(betterproto.Message):
    challenge_request: "RegisterAuthenticatorBeginResponseChallengeRequest" = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginResponseChallengeRequest(betterproto.Message):
    fido: "RegisterAuthenticatorBeginResponseChallengeRequestFido" = (
        betterproto.message_field(1, group="type")
    )
    totp: "RegisterAuthenticatorBeginResponseChallengeRequestTotp" = (
        betterproto.message_field(2, group="type")
    )
    tpm: "RegisterAuthenticatorBeginResponseChallengeRequestTpm" = (
        betterproto.message_field(3, group="type")
    )


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginResponseChallengeRequestFido(betterproto.Message):
    request: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginResponseChallengeRequestTotp(betterproto.Message):
    url: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginResponseChallengeRequestTpm(betterproto.Message):
    encrypted_credential: (
        "RegisterAuthenticatorBeginResponseChallengeRequestTpmEncryptedCredential"
    ) = betterproto.message_field(1)
    ak_bytes: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorBeginResponseChallengeRequestTpmEncryptedCredential(
    betterproto.Message
):
    credential: bytes = betterproto.bytes_field(1)
    secret: bytes = betterproto.bytes_field(2)


@dataclass(eq=False, repr=False)
class Authenticator(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    """APIVersion is the API version of the object."""

    kind: str = betterproto.string_field(2)
    """Kind is the resource name (i.e. `Group`)."""

    metadata: "__meta_v1__.Metadata" = betterproto.message_field(3)
    """octelium.api.main.meta.v1.Metadata is the object's metadata."""

    spec: "AuthenticatorSpec" = betterproto.message_field(4)
    """Spec is the Group specification."""

    status: "AuthenticatorStatus" = betterproto.message_field(5)
    """Status is the current status of the Group."""


@dataclass(eq=False, repr=False)
class AuthenticatorSpec(betterproto.Message):
    display_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AuthenticatorStatus(betterproto.Message):
    is_registered: bool = betterproto.bool_field(1)
    type: "AuthenticatorStatusType" = betterproto.enum_field(2)
    description: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class AuthenticatorList(betterproto.Message):
    api_version: str = betterproto.string_field(1)
    """APIVersion is the API version of the object."""

    kind: str = betterproto.string_field(2)
    """Kind is the resource name (i.e. `GroupList`)."""

    items: List["Authenticator"] = betterproto.message_field(3)
    """Items is the list of Groups."""

    list_response_meta: "__meta_v1__.ListResponseMeta" = betterproto.message_field(4)
    """ListResponseMeta is common information about the list."""


@dataclass(eq=False, repr=False)
class ListAuthenticatorOptions(betterproto.Message):
    page: int = betterproto.uint32_field(1)
    """Page is the page number. Starts at 0"""

    items_per_page: int = betterproto.uint32_field(2)
    """ItemsPerPage is the number of items per page"""


@dataclass(eq=False, repr=False)
class CreateAuthenticatorRequest(betterproto.Message):
    type: "AuthenticatorStatusType" = betterproto.enum_field(1)
    display_name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorFinishRequest(betterproto.Message):
    authenticator_ref: "__meta_v1__.ObjectReference" = betterproto.message_field(1)
    challenge_response: "ChallengeResponse" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class RegisterAuthenticatorFinishResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChallengeResponse(betterproto.Message):
    fido: "ChallengeResponseFido" = betterproto.message_field(1, group="type")
    totp: "ChallengeResponseTotp" = betterproto.message_field(2, group="type")
    tpm: "ChallengeResponseTpm" = betterproto.message_field(3, group="type")


@dataclass(eq=False, repr=False)
class ChallengeResponseFido(betterproto.Message):
    response: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ChallengeResponseTotp(betterproto.Message):
    response: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ChallengeResponseTpm(betterproto.Message):
    response: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class AuthenticateWithAuthenticatorRequest(betterproto.Message):
    authenticator_ref: "__meta_v1__.ObjectReference" = betterproto.message_field(1)
    challenge_response: "ChallengeResponse" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class GetAvailableAuthenticatorRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetAvailableAuthenticatorResponse(betterproto.Message):
    main_authenticator: "Authenticator" = betterproto.message_field(1)
    available_authenticators: List["Authenticator"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AuthenticateWithPasskeyBeginRequest(betterproto.Message):
    query: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AuthenticateWithPasskeyBeginResponse(betterproto.Message):
    request: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AuthenticateWithPasskeyRequest(betterproto.Message):
    response: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RunDeviceProbeBeginRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class RunDeviceProbeBeginResponse(betterproto.Message):
    attempt_uid: str = betterproto.string_field(1)
    probes: List["DeviceProbe"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class DeviceProbe(betterproto.Message):
    probe_id: str = betterproto.string_field(1)
    require_elevation: bool = betterproto.bool_field(2)
    run_command: "DeviceProbeRunCommand" = betterproto.message_field(3, group="type")
    read_file: "DeviceProbeReadFile" = betterproto.message_field(4, group="type")
    read_registry: "DeviceProbeReadRegistry" = betterproto.message_field(
        5, group="type"
    )


@dataclass(eq=False, repr=False)
class DeviceProbeRunCommand(betterproto.Message):
    command: str = betterproto.string_field(1)
    args: List[str] = betterproto.string_field(2)
    timeout_seconds: int = betterproto.uint32_field(3)
    max_output_bytes: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class DeviceProbeReadFile(betterproto.Message):
    path: str = betterproto.string_field(1)
    max_bytes: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class DeviceProbeReadRegistry(betterproto.Message):
    key: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class DeviceProbeResult(betterproto.Message):
    probe_id: str = betterproto.string_field(1)
    output: bytes = betterproto.bytes_field(2, group="type")
    error: str = betterproto.string_field(3, group="type")


@dataclass(eq=False, repr=False)
class RunDeviceProbeFinishRequest(betterproto.Message):
    attempt_uid: str = betterproto.string_field(1)
    results: List["DeviceProbeResult"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class RunDeviceProbeFinishResponse(betterproto.Message):
    pass


class MainServiceStub(betterproto.ServiceStub):
    async def authenticate_with_authentication_token(
        self,
        authenticate_with_authentication_token_request: "AuthenticateWithAuthenticationTokenRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SessionToken":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithAuthenticationToken",
            authenticate_with_authentication_token_request,
            SessionToken,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authenticate_with_assertion(
        self,
        authenticate_with_assertion_request: "AuthenticateWithAssertionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SessionToken":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithAssertion",
            authenticate_with_assertion_request,
            SessionToken,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authenticate_with_refresh_token(
        self,
        authenticate_with_refresh_token_request: "AuthenticateWithRefreshTokenRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SessionToken":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithRefreshToken",
            authenticate_with_refresh_token_request,
            SessionToken,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authenticate_with_authenticator(
        self,
        authenticate_with_authenticator_request: "AuthenticateWithAuthenticatorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SessionToken":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithAuthenticator",
            authenticate_with_authenticator_request,
            SessionToken,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def logout(
        self,
        logout_request: "LogoutRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "LogoutResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/Logout",
            logout_request,
            LogoutResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_device_begin(
        self,
        register_device_begin_request: "RegisterDeviceBeginRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RegisterDeviceBeginResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/RegisterDeviceBegin",
            register_device_begin_request,
            RegisterDeviceBeginResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_device_finish(
        self,
        register_device_finish_request: "RegisterDeviceFinishRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RegisterDeviceFinishResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/RegisterDeviceFinish",
            register_device_finish_request,
            RegisterDeviceFinishResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_authenticator(
        self,
        meta_v1_get_options: "__meta_v1__.GetOptions",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Authenticator":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/GetAuthenticator",
            meta_v1_get_options,
            Authenticator,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def create_authenticator(
        self,
        create_authenticator_request: "CreateAuthenticatorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Authenticator":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/CreateAuthenticator",
            create_authenticator_request,
            Authenticator,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_authenticator(
        self,
        authenticator: "Authenticator",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Authenticator":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/UpdateAuthenticator",
            authenticator,
            Authenticator,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_authenticator(
        self,
        list_authenticator_options: "ListAuthenticatorOptions",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AuthenticatorList":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/ListAuthenticator",
            list_authenticator_options,
            AuthenticatorList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_authenticator(
        self,
        meta_v1_delete_options: "__meta_v1__.DeleteOptions",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__meta_v1__.OperationResult":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/DeleteAuthenticator",
            meta_v1_delete_options,
            __meta_v1__.OperationResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_authenticator_begin(
        self,
        register_authenticator_begin_request: "RegisterAuthenticatorBeginRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RegisterAuthenticatorBeginResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/RegisterAuthenticatorBegin",
            register_authenticator_begin_request,
            RegisterAuthenticatorBeginResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_authenticator_finish(
        self,
        register_authenticator_finish_request: "RegisterAuthenticatorFinishRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RegisterAuthenticatorFinishResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/RegisterAuthenticatorFinish",
            register_authenticator_finish_request,
            RegisterAuthenticatorFinishResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authenticate_authenticator_begin(
        self,
        authenticate_authenticator_begin_request: "AuthenticateAuthenticatorBeginRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AuthenticateAuthenticatorBeginResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateAuthenticatorBegin",
            authenticate_authenticator_begin_request,
            AuthenticateAuthenticatorBeginResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_available_authenticator(
        self,
        get_available_authenticator_request: "GetAvailableAuthenticatorRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetAvailableAuthenticatorResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/GetAvailableAuthenticator",
            get_available_authenticator_request,
            GetAvailableAuthenticatorResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authenticate_with_passkey_begin(
        self,
        authenticate_with_passkey_begin_request: "AuthenticateWithPasskeyBeginRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AuthenticateWithPasskeyBeginResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithPasskeyBegin",
            authenticate_with_passkey_begin_request,
            AuthenticateWithPasskeyBeginResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authenticate_with_passkey(
        self,
        authenticate_with_passkey_request: "AuthenticateWithPasskeyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SessionToken":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithPasskey",
            authenticate_with_passkey_request,
            SessionToken,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def run_device_probe_begin(
        self,
        run_device_probe_begin_request: "RunDeviceProbeBeginRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RunDeviceProbeBeginResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/RunDeviceProbeBegin",
            run_device_probe_begin_request,
            RunDeviceProbeBeginResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def run_device_probe_finish(
        self,
        run_device_probe_finish_request: "RunDeviceProbeFinishRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RunDeviceProbeFinishResponse":
        return await self._unary_unary(
            "/octelium.api.main.auth.v1.MainService/RunDeviceProbeFinish",
            run_device_probe_finish_request,
            RunDeviceProbeFinishResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class MainServiceBase(ServiceBase):

    async def authenticate_with_authentication_token(
        self,
        authenticate_with_authentication_token_request: "AuthenticateWithAuthenticationTokenRequest",
    ) -> "SessionToken":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authenticate_with_assertion(
        self, authenticate_with_assertion_request: "AuthenticateWithAssertionRequest"
    ) -> "SessionToken":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authenticate_with_refresh_token(
        self,
        authenticate_with_refresh_token_request: "AuthenticateWithRefreshTokenRequest",
    ) -> "SessionToken":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authenticate_with_authenticator(
        self,
        authenticate_with_authenticator_request: "AuthenticateWithAuthenticatorRequest",
    ) -> "SessionToken":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def logout(self, logout_request: "LogoutRequest") -> "LogoutResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def register_device_begin(
        self, register_device_begin_request: "RegisterDeviceBeginRequest"
    ) -> "RegisterDeviceBeginResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def register_device_finish(
        self, register_device_finish_request: "RegisterDeviceFinishRequest"
    ) -> "RegisterDeviceFinishResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_authenticator(
        self, meta_v1_get_options: "__meta_v1__.GetOptions"
    ) -> "Authenticator":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def create_authenticator(
        self, create_authenticator_request: "CreateAuthenticatorRequest"
    ) -> "Authenticator":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_authenticator(
        self, authenticator: "Authenticator"
    ) -> "Authenticator":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_authenticator(
        self, list_authenticator_options: "ListAuthenticatorOptions"
    ) -> "AuthenticatorList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_authenticator(
        self, meta_v1_delete_options: "__meta_v1__.DeleteOptions"
    ) -> "__meta_v1__.OperationResult":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def register_authenticator_begin(
        self, register_authenticator_begin_request: "RegisterAuthenticatorBeginRequest"
    ) -> "RegisterAuthenticatorBeginResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def register_authenticator_finish(
        self,
        register_authenticator_finish_request: "RegisterAuthenticatorFinishRequest",
    ) -> "RegisterAuthenticatorFinishResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authenticate_authenticator_begin(
        self,
        authenticate_authenticator_begin_request: "AuthenticateAuthenticatorBeginRequest",
    ) -> "AuthenticateAuthenticatorBeginResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_available_authenticator(
        self, get_available_authenticator_request: "GetAvailableAuthenticatorRequest"
    ) -> "GetAvailableAuthenticatorResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authenticate_with_passkey_begin(
        self,
        authenticate_with_passkey_begin_request: "AuthenticateWithPasskeyBeginRequest",
    ) -> "AuthenticateWithPasskeyBeginResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authenticate_with_passkey(
        self, authenticate_with_passkey_request: "AuthenticateWithPasskeyRequest"
    ) -> "SessionToken":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def run_device_probe_begin(
        self, run_device_probe_begin_request: "RunDeviceProbeBeginRequest"
    ) -> "RunDeviceProbeBeginResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def run_device_probe_finish(
        self, run_device_probe_finish_request: "RunDeviceProbeFinishRequest"
    ) -> "RunDeviceProbeFinishResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_authenticate_with_authentication_token(
        self,
        stream: "grpclib.server.Stream[AuthenticateWithAuthenticationTokenRequest, SessionToken]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_with_authentication_token(request)
        await stream.send_message(response)

    async def __rpc_authenticate_with_assertion(
        self,
        stream: "grpclib.server.Stream[AuthenticateWithAssertionRequest, SessionToken]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_with_assertion(request)
        await stream.send_message(response)

    async def __rpc_authenticate_with_refresh_token(
        self,
        stream: "grpclib.server.Stream[AuthenticateWithRefreshTokenRequest, SessionToken]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_with_refresh_token(request)
        await stream.send_message(response)

    async def __rpc_authenticate_with_authenticator(
        self,
        stream: "grpclib.server.Stream[AuthenticateWithAuthenticatorRequest, SessionToken]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_with_authenticator(request)
        await stream.send_message(response)

    async def __rpc_logout(
        self, stream: "grpclib.server.Stream[LogoutRequest, LogoutResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.logout(request)
        await stream.send_message(response)

    async def __rpc_register_device_begin(
        self,
        stream: "grpclib.server.Stream[RegisterDeviceBeginRequest, RegisterDeviceBeginResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.register_device_begin(request)
        await stream.send_message(response)

    async def __rpc_register_device_finish(
        self,
        stream: "grpclib.server.Stream[RegisterDeviceFinishRequest, RegisterDeviceFinishResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.register_device_finish(request)
        await stream.send_message(response)

    async def __rpc_get_authenticator(
        self, stream: "grpclib.server.Stream[__meta_v1__.GetOptions, Authenticator]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_authenticator(request)
        await stream.send_message(response)

    async def __rpc_create_authenticator(
        self, stream: "grpclib.server.Stream[CreateAuthenticatorRequest, Authenticator]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.create_authenticator(request)
        await stream.send_message(response)

    async def __rpc_update_authenticator(
        self, stream: "grpclib.server.Stream[Authenticator, Authenticator]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_authenticator(request)
        await stream.send_message(response)

    async def __rpc_list_authenticator(
        self,
        stream: "grpclib.server.Stream[ListAuthenticatorOptions, AuthenticatorList]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_authenticator(request)
        await stream.send_message(response)

    async def __rpc_delete_authenticator(
        self,
        stream: "grpclib.server.Stream[__meta_v1__.DeleteOptions, __meta_v1__.OperationResult]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_authenticator(request)
        await stream.send_message(response)

    async def __rpc_register_authenticator_begin(
        self,
        stream: "grpclib.server.Stream[RegisterAuthenticatorBeginRequest, RegisterAuthenticatorBeginResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.register_authenticator_begin(request)
        await stream.send_message(response)

    async def __rpc_register_authenticator_finish(
        self,
        stream: "grpclib.server.Stream[RegisterAuthenticatorFinishRequest, RegisterAuthenticatorFinishResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.register_authenticator_finish(request)
        await stream.send_message(response)

    async def __rpc_authenticate_authenticator_begin(
        self,
        stream: "grpclib.server.Stream[AuthenticateAuthenticatorBeginRequest, AuthenticateAuthenticatorBeginResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_authenticator_begin(request)
        await stream.send_message(response)

    async def __rpc_get_available_authenticator(
        self,
        stream: "grpclib.server.Stream[GetAvailableAuthenticatorRequest, GetAvailableAuthenticatorResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_available_authenticator(request)
        await stream.send_message(response)

    async def __rpc_authenticate_with_passkey_begin(
        self,
        stream: "grpclib.server.Stream[AuthenticateWithPasskeyBeginRequest, AuthenticateWithPasskeyBeginResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_with_passkey_begin(request)
        await stream.send_message(response)

    async def __rpc_authenticate_with_passkey(
        self,
        stream: "grpclib.server.Stream[AuthenticateWithPasskeyRequest, SessionToken]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.authenticate_with_passkey(request)
        await stream.send_message(response)

    async def __rpc_run_device_probe_begin(
        self,
        stream: "grpclib.server.Stream[RunDeviceProbeBeginRequest, RunDeviceProbeBeginResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.run_device_probe_begin(request)
        await stream.send_message(response)

    async def __rpc_run_device_probe_finish(
        self,
        stream: "grpclib.server.Stream[RunDeviceProbeFinishRequest, RunDeviceProbeFinishResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.run_device_probe_finish(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithAuthenticationToken": grpclib.const.Handler(
                self.__rpc_authenticate_with_authentication_token,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateWithAuthenticationTokenRequest,
                SessionToken,
            ),
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithAssertion": grpclib.const.Handler(
                self.__rpc_authenticate_with_assertion,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateWithAssertionRequest,
                SessionToken,
            ),
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithRefreshToken": grpclib.const.Handler(
                self.__rpc_authenticate_with_refresh_token,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateWithRefreshTokenRequest,
                SessionToken,
            ),
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithAuthenticator": grpclib.const.Handler(
                self.__rpc_authenticate_with_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateWithAuthenticatorRequest,
                SessionToken,
            ),
            "/octelium.api.main.auth.v1.MainService/Logout": grpclib.const.Handler(
                self.__rpc_logout,
                grpclib.const.Cardinality.UNARY_UNARY,
                LogoutRequest,
                LogoutResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/RegisterDeviceBegin": grpclib.const.Handler(
                self.__rpc_register_device_begin,
                grpclib.const.Cardinality.UNARY_UNARY,
                RegisterDeviceBeginRequest,
                RegisterDeviceBeginResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/RegisterDeviceFinish": grpclib.const.Handler(
                self.__rpc_register_device_finish,
                grpclib.const.Cardinality.UNARY_UNARY,
                RegisterDeviceFinishRequest,
                RegisterDeviceFinishResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/GetAuthenticator": grpclib.const.Handler(
                self.__rpc_get_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                __meta_v1__.GetOptions,
                Authenticator,
            ),
            "/octelium.api.main.auth.v1.MainService/CreateAuthenticator": grpclib.const.Handler(
                self.__rpc_create_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateAuthenticatorRequest,
                Authenticator,
            ),
            "/octelium.api.main.auth.v1.MainService/UpdateAuthenticator": grpclib.const.Handler(
                self.__rpc_update_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                Authenticator,
                Authenticator,
            ),
            "/octelium.api.main.auth.v1.MainService/ListAuthenticator": grpclib.const.Handler(
                self.__rpc_list_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListAuthenticatorOptions,
                AuthenticatorList,
            ),
            "/octelium.api.main.auth.v1.MainService/DeleteAuthenticator": grpclib.const.Handler(
                self.__rpc_delete_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                __meta_v1__.DeleteOptions,
                __meta_v1__.OperationResult,
            ),
            "/octelium.api.main.auth.v1.MainService/RegisterAuthenticatorBegin": grpclib.const.Handler(
                self.__rpc_register_authenticator_begin,
                grpclib.const.Cardinality.UNARY_UNARY,
                RegisterAuthenticatorBeginRequest,
                RegisterAuthenticatorBeginResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/RegisterAuthenticatorFinish": grpclib.const.Handler(
                self.__rpc_register_authenticator_finish,
                grpclib.const.Cardinality.UNARY_UNARY,
                RegisterAuthenticatorFinishRequest,
                RegisterAuthenticatorFinishResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/AuthenticateAuthenticatorBegin": grpclib.const.Handler(
                self.__rpc_authenticate_authenticator_begin,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateAuthenticatorBeginRequest,
                AuthenticateAuthenticatorBeginResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/GetAvailableAuthenticator": grpclib.const.Handler(
                self.__rpc_get_available_authenticator,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAvailableAuthenticatorRequest,
                GetAvailableAuthenticatorResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithPasskeyBegin": grpclib.const.Handler(
                self.__rpc_authenticate_with_passkey_begin,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateWithPasskeyBeginRequest,
                AuthenticateWithPasskeyBeginResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/AuthenticateWithPasskey": grpclib.const.Handler(
                self.__rpc_authenticate_with_passkey,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthenticateWithPasskeyRequest,
                SessionToken,
            ),
            "/octelium.api.main.auth.v1.MainService/RunDeviceProbeBegin": grpclib.const.Handler(
                self.__rpc_run_device_probe_begin,
                grpclib.const.Cardinality.UNARY_UNARY,
                RunDeviceProbeBeginRequest,
                RunDeviceProbeBeginResponse,
            ),
            "/octelium.api.main.auth.v1.MainService/RunDeviceProbeFinish": grpclib.const.Handler(
                self.__rpc_run_device_probe_finish,
                grpclib.const.Cardinality.UNARY_UNARY,
                RunDeviceProbeFinishRequest,
                RunDeviceProbeFinishResponse,
            ),
        }
