"""Render public docstrings and signatures into the checked-in API reference."""

from __future__ import annotations

import inspect
from pathlib import Path

import cordium

root = Path(__file__).resolve().parents[1]
lines = [
    "# Public API reference",
    "",
    "Generated by `python scripts/generate_reference.py`. The guide is in [README](../README.md).",
    "",
    "Async methods require `await`; async iterators use `async for`. Resource handles are obtained from a client, not constructed directly. All durations are seconds.",
    "",
]
for name in cordium.__all__:
    value = getattr(cordium, name)
    if name in ("proto", "meta"):
        lines += [
            f"## `{name}`",
            "",
            f"Generated protobuf module: `{value.__name__}`. Message fields carry protocol documentation.",
            "",
        ]
        continue
    if not (inspect.isclass(value) or inspect.isfunction(value)):
        lines += [f"## `{name}`", "", f"Type alias: `{value!s}`.", ""]
        continue
    lines += [f"## `{name}`", "", inspect.getdoc(value) or name, ""]
    if inspect.isfunction(value) or name in (
        "Cordium",
        "AsyncCordium",
        "Ref",
        "AccessToken",
        "Assertion",
        "AssertionFile",
        "AuthenticationToken",
        "Application",
        "Resources",
        "Task",
        "VolumeMount",
        "SecretRef",
        "ExecResult",
        "ExecOutput",
        "Page",
        "TerminalEvent",
        "CordiumError",
        "ExecError",
        "WorkspaceFailureError",
    ):
        lines += ["```python", f"{name}{inspect.signature(value)}", "```", ""]
    if inspect.isclass(value) and value.__module__.startswith("cordium"):
        for member_name, member in vars(value).items():
            if member_name.startswith("_"):
                continue
            if isinstance(member, property):
                lines += [f"### `{name}.{member_name}`", "", inspect.getdoc(member) or "", ""]
            elif inspect.isfunction(member):
                prefix = (
                    "async "
                    if inspect.iscoroutinefunction(member) or inspect.isasyncgenfunction(member)
                    else ""
                )
                lines += [
                    f"### `{name}.{member_name}`",
                    "",
                    "```python",
                    f"{prefix}{member_name}{inspect.signature(member)}",
                    "```",
                    "",
                    inspect.getdoc(member) or "",
                    "",
                ]
path = root / "packages/cordium/docs/api.md"
path.write_text("\n".join(lines))
