"""Generate the explicitly typed sync facade from public async signatures.

Run after changing public async interfaces. Bodies/docstrings are shared through
forwarding, while signatures remain visible to IDEs, type checkers and help().
"""

from __future__ import annotations

import ast
import copy
import subprocess
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = root / "packages/cordium/src/cordium"
modules = ("resources", "files", "terminals", "workspaces", "exec", "client")
classes = [
    (module, node)
    for module in modules
    for node in ast.parse((source / f"{module}.py").read_text()).body
    if isinstance(node, ast.ClassDef) and node.name.startswith("Async")
]
names = {node.name: node.name.removeprefix("Async") for _, node in classes}
names["AsyncStream"] = "Stream"

header = '''"""Blocking Cordium facade. Generated by scripts/generate_sync.py; do not hand edit."""
from __future__ import annotations

import ssl
from collections.abc import AsyncIterator, Awaitable, Callable, Iterator, Mapping, Sequence
from datetime import datetime
from pathlib import Path
from types import TracebackType
from typing import Generic, Literal, TypeVar, Unpack, cast

import httpx
from octelium.api.main.cordium import v1 as p

from ._portal import Portal
from .auth import Credentials
from .models import ExecOutput, ExecResult, Page, Reference, TerminalEvent
from .resources import JsonValue, Role, SecretValue
from .spec import Resources, SecretRef, Task, VolumeMount, WorkspaceOptions
from .workspaces import State
'''
for module in modules:
    imported = [node.name for mod, node in classes if mod == module]
    header += f"from .{module} import {', '.join(imported)}\n"
header += '''
T = TypeVar("T")


class _Facade(Generic[T]):
    def __init__(self, portal: Portal, value: T) -> None:
        self._portal, self._async = portal, value


async def _next(iterator: AsyncIterator[T]) -> tuple[bool, T | None]:
    try:
        return True, await anext(iterator)
    except StopAsyncIteration:
        return False, None


class Stream(Generic[T]):
    """Single-consumer blocking iterator. Use with to close on early loop exit."""
    def __init__(self, portal: Portal, iterator: AsyncIterator[T]) -> None:
        self._portal, self._iterator, self._closed = portal, iterator, False

    def __iter__(self) -> Stream[T]:
        """Return this stream."""
        return self

    def __next__(self) -> T:
        """Wait for the next item; propagate server errors and deadlines."""
        if self._closed: raise StopIteration
        has_value, value = self._portal.invoke(lambda: _next(self._iterator))
        if not has_value:
            self._closed = True
            raise StopIteration
        from typing import cast
        return cast(T, value)

    def close(self) -> None:
        """Cancel this subscription; never delete remote resources."""
        if not self._closed:
            self._closed = True
            if hasattr(self._iterator, "aclose"):
                self._portal.release(self._iterator.aclose)

    def __enter__(self) -> Stream[T]:
        """Return the stream; closing is guaranteed on context exit."""
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None:
        """Release this subscription."""
        self.close()


async def _workspace_items(portal: Portal, iterator: AsyncIterator[AsyncWorkspace]) -> AsyncIterator[Workspace]:
    try:
        async for item in iterator:
            yield Workspace(portal, item)
    finally:
        if hasattr(iterator, "aclose"): await iterator.aclose()
'''


class Rewrite(ast.NodeTransformer):
    def visit_Name(self, node: ast.Name) -> ast.Name:
        return ast.Name(
            id=names.get(node.id, "Iterator" if node.id == "AsyncIterator" else node.id),
            ctx=node.ctx,
        )


result = header
for _module, cls in classes:
    name = names[cls.name]
    result += f"\n\nclass {name}(_Facade[{cls.name}]):\n"
    doc = (
        (ast.get_docstring(cls) or name)
        .replace("async with", "with")
        .replace("aclose()", "close()")
        .replace(
            "Native asyncio SDK, bound to its first event loop. Use ``with``.",
            "Blocking SDK with one owned event-loop thread. Use ``with``.",
        )
    )
    if name == "Cordium":
        doc = """Blocking Cordium SDK with one owned event-loop thread; use with.

        Safe for calls from multiple threads. Create a new client after fork.
        domain selects the Cluster, and RPCs default to octelium-api.<domain>:443.
        auth defaults to Octelium credential environment variables. TLS verifies
        peers; use an SSLContext for custom CAs. Construction does not contact
        the Cluster. close() cancels operations and joins the thread.
        """
    result += "    " + repr(doc) + "\n"
    if name == "Cordium":
        result += '''
    def __init__(self, domain: str | None = None, *, auth: Credentials | None = None, host: str | None = None, port: int = 443, tls: ssl.SSLContext | bool = True, authorized_http_hosts: Sequence[str] = (), allow_insecure_http: bool = False) -> None:
        portal = Portal()
        try:
            value = portal.invoke(lambda: AsyncCordium(domain, auth=auth, host=host, port=port, tls=tls, authorized_http_hosts=authorized_http_hosts, allow_insecure_http=allow_insecure_http))
        except BaseException:
            async def cleanup() -> None: pass
            portal.close(cleanup)
            raise
        super().__init__(portal, value)

    def call(self, operation: Callable[[AsyncCordium], Awaitable[T]]) -> T:
        """Run an advanced async operation on the owned loop, including generated raw RPCs.

        Example: client.call(lambda c: c.raw.main.get_workspace(request, timeout=10)).
        Callbacks must not call blocking methods on this same client.
        """
        return self._portal.invoke(lambda: operation(self._async))
'''
    for method in cls.body:
        if (
            not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef))
            or method.name.startswith("_")
            or (name == "Cordium" and method.name == "raw")
        ):
            continue
        if isinstance(method, ast.FunctionDef) and any(
            isinstance(dec, ast.Name) and dec.id == "staticmethod" for dec in method.decorator_list
        ):
            continue
        prop = any(
            isinstance(dec, ast.Name) and dec.id == "property" for dec in method.decorator_list
        )
        annotation = ast.unparse(method.returns) if method.returns else "None"
        args = ast.unparse(Rewrite().visit(copy.deepcopy(method.args)))
        returned = (
            ast.unparse(Rewrite().visit(copy.deepcopy(method.returns)))
            if method.returns
            else "None"
        )
        if annotation.startswith("AsyncIterator["):
            returned = returned.replace("Iterator[", "Stream[", 1)
        method_name = "close" if method.name == "aclose" else method.name
        signature = f"    def {method_name}({args}) -> {returned}:\n"
        if prop:
            result += "\n    @property\n"
        else:
            result += "\n"
        result += signature
        method_doc = (
            (ast.get_docstring(method) or method.name)
            .replace("async with await", "with")
            .replace("async with", "with")
            .replace("async context", "context")
            .replace("aclose()", "close()")
        )
        result += "        " + repr(method_doc) + "\n"
        if name == "Cordium" and method.name == "aclose":
            result += "        self._portal.close(self._async.aclose)\n"
            continue
        passed = [a.arg for a in method.args.posonlyargs + method.args.args if a.arg != "self"]
        passed += [f"{a.arg}={a.arg}" for a in method.args.kwonlyargs]
        if method.args.vararg:
            passed.append("*" + method.args.vararg.arg)
        if method.args.kwarg:
            passed.append("**" + method.args.kwarg.arg)
        call = f"self._async.{method.name}" + ("" if prop else f"({', '.join(passed)})")
        invoke = f"self._portal.invoke(lambda: {call})"
        if method.name == "aclose":
            body = "self._portal.release(self._async.aclose)"
        elif annotation in names:
            body = f"return {names[annotation]}(self._portal, {invoke})"
        elif annotation == "State":
            body = f"return cast(State, {invoke})"
        elif annotation == "Page[AsyncWorkspace]":
            body = f"value = {invoke}\n        return Page(tuple(Workspace(self._portal, item) for item in value.items), value.page, value.page_size, value.total_count, value.has_more)"
        elif annotation == "AsyncIterator[AsyncWorkspace]":
            body = f"return Stream(self._portal, _workspace_items(self._portal, {invoke}))"
        elif annotation.startswith(("AsyncIterator[", "AsyncStream[")):
            body = f"return Stream(self._portal, {invoke})"
        else:
            body = f"return {invoke}" if annotation != "None" else invoke
        result += "        " + body + "\n"
    if name in ("Cordium", "ExecSession", "Terminal"):
        result += f'''
    def __enter__(self) -> {name}:
        """Enter the owned async context and return this blocking handle."""
        self._portal.invoke(self._async.__aenter__)
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None:
        """Release local resources on context exit."""
        self.close()
'''
    if name == "ExecSession":
        result += '''
    def __iter__(self) -> Iterator[ExecOutput]:
        """Iterate ordered binary output; use the session context manager for early exit."""
        self._portal.invoke(self._async.__aiter__)
        return Stream(self._portal, self._async)
'''
path = source / "sync.py"
path.write_text(result)
subprocess.run([sys.executable, "-m", "ruff", "format", str(path)], check=True)
subprocess.run([sys.executable, "-m", "ruff", "check", str(path), "--fix"], check=True)
